// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.mms;

[global::ProtoBuf.ProtoContract()]
public partial class Client : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"node_id", IsRequired = true)]
    public uint NodeId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"pcb_serial", IsRequired = true)]
    public string PcbSerial { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"loc_id", IsRequired = true)]
    public string LocId { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"subnet_id")]
    [global::System.ComponentModel.DefaultValue("")]
    public string SubnetId
    {
        get => __pbn__SubnetId ?? "";
        set => __pbn__SubnetId = value;
    }
    public bool ShouldSerializeSubnetId() => __pbn__SubnetId != null;
    public void ResetSubnetId() => __pbn__SubnetId = null;
    private string __pbn__SubnetId;

    [global::ProtoBuf.ProtoMember(5, Name = @"pref_code", IsRequired = true)]
    public uint PrefCode { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"global_ipaddress")]
    [global::System.ComponentModel.DefaultValue("")]
    public string GlobalIpaddress
    {
        get => __pbn__GlobalIpaddress ?? "";
        set => __pbn__GlobalIpaddress = value;
    }
    public bool ShouldSerializeGlobalIpaddress() => __pbn__GlobalIpaddress != null;
    public void ResetGlobalIpaddress() => __pbn__GlobalIpaddress = null;
    private string __pbn__GlobalIpaddress;

    [global::ProtoBuf.ProtoMember(7, Name = @"global_port")]
    public uint GlobalPort
    {
        get => __pbn__GlobalPort.GetValueOrDefault();
        set => __pbn__GlobalPort = value;
    }
    public bool ShouldSerializeGlobalPort() => __pbn__GlobalPort != null;
    public void ResetGlobalPort() => __pbn__GlobalPort = null;
    private uint? __pbn__GlobalPort;

    [global::ProtoBuf.ProtoMember(8, Name = @"local_ipaddress")]
    [global::System.ComponentModel.DefaultValue("")]
    public string LocalIpaddress
    {
        get => __pbn__LocalIpaddress ?? "";
        set => __pbn__LocalIpaddress = value;
    }
    public bool ShouldSerializeLocalIpaddress() => __pbn__LocalIpaddress != null;
    public void ResetLocalIpaddress() => __pbn__LocalIpaddress = null;
    private string __pbn__LocalIpaddress;

    [global::ProtoBuf.ProtoMember(9, Name = @"local_port")]
    public uint LocalPort
    {
        get => __pbn__LocalPort.GetValueOrDefault();
        set => __pbn__LocalPort = value;
    }
    public bool ShouldSerializeLocalPort() => __pbn__LocalPort != null;
    public void ResetLocalPort() => __pbn__LocalPort = null;
    private uint? __pbn__LocalPort;

    [global::ProtoBuf.ProtoMember(100, Name = @"nat_mapping_type", IsRequired = true)]
    public NatMappingType NatMappingType { get; set; }

    [global::ProtoBuf.ProtoMember(101, Name = @"nat_filtering_type", IsRequired = true)]
    public NatFilteringType NatFilteringType { get; set; }

    [global::ProtoBuf.ProtoMember(102, Name = @"nat_allocation_policy")]
    [global::System.ComponentModel.DefaultValue(NatAllocationPolicy.NaNone)]
    public NatAllocationPolicy NatAllocationPolicy
    {
        get => __pbn__NatAllocationPolicy ?? NatAllocationPolicy.NaNone;
        set => __pbn__NatAllocationPolicy = value;
    }
    public bool ShouldSerializeNatAllocationPolicy() => __pbn__NatAllocationPolicy != null;
    public void ResetNatAllocationPolicy() => __pbn__NatAllocationPolicy = null;
    private NatAllocationPolicy? __pbn__NatAllocationPolicy;

    [global::ProtoBuf.ProtoMember(200, Name = @"property")]
    public global::System.Collections.Generic.List<Property> Properties { get; } = new();

    [global::ProtoBuf.ProtoContract()]
    public partial class Property : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"property_id", IsRequired = true)]
        public uint PropertyId { get; set; } // 0

        [global::ProtoBuf.ProtoMember(2, Name = @"property_value", IsRequired = true)]
        public string PropertyValue { get; set; } // "Y" or "N"

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192