// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.mms;

[global::ProtoBuf.ProtoContract()]
public partial class World : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"mucha_game_id", IsRequired = true)]
    public string MuchaGameId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"version", IsRequired = true)]
    public uint Version { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"world_id", IsRequired = true)]
    public uint WorldId { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192