// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

//#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Request : global::ProtoBuf.IExtensible
{
    // 1300
    [global::ProtoBuf.ProtoContract()]
    public partial class CheckCommunication : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start_date", IsRequired = true)]
        public ulong StartDate { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"end_date", IsRequired = true)]
        public ulong EndDate { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"skill_point_mobile_suit_id", IsRequired = true)]
        public uint SkillPointMobileSuitId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"pilot_id", IsRequired = true)]
        public uint PilotId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"line_type", IsRequired = true)]
        public OnlineLineType LineType { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"apply_id", IsRequired = true)]
        public uint ApplyId { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"matching_try_num", IsRequired = true)]
        public uint MatchingTryNum { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public StunResult stun_result { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"found_player_flag", IsRequired = true)]
        public bool FoundPlayerFlag { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"udp_hp_result", IsRequired = true)]
        public UdpHpResultType UdpHpResult { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"players")]
        public global::System.Collections.Generic.List<OtherPlayerInfo> Players { get; } = new();

        [global::ProtoBuf.ProtoMember(12, Name = @"class_id")]
        public uint ClassId
        {
            get => __pbn__ClassId.GetValueOrDefault();
            set => __pbn__ClassId = value;
        }
        public bool ShouldSerializeClassId() => __pbn__ClassId != null;
        public void ResetClassId() => __pbn__ClassId = null;
        private uint? __pbn__ClassId;

        [global::ProtoBuf.ProtoMember(13, Name = @"level_id")]
        public uint LevelId
        {
            get => __pbn__LevelId.GetValueOrDefault();
            set => __pbn__LevelId = value;
        }
        public bool ShouldSerializeLevelId() => __pbn__LevelId != null;
        public void ResetLevelId() => __pbn__LevelId = null;
        private uint? __pbn__LevelId;

        [global::ProtoBuf.ProtoMember(14, Name = @"matching_rank_free")]
        public uint MatchingRankFree
        {
            get => __pbn__MatchingRankFree.GetValueOrDefault();
            set => __pbn__MatchingRankFree = value;
        }
        public bool ShouldSerializeMatchingRankFree() => __pbn__MatchingRankFree != null;
        public void ResetMatchingRankFree() => __pbn__MatchingRankFree = null;
        private uint? __pbn__MatchingRankFree;

        [global::ProtoBuf.ProtoMember(15, Name = @"matching_rank_fes")]
        public uint MatchingRankFes
        {
            get => __pbn__MatchingRankFes.GetValueOrDefault();
            set => __pbn__MatchingRankFes = value;
        }
        public bool ShouldSerializeMatchingRankFes() => __pbn__MatchingRankFes != null;
        public void ResetMatchingRankFes() => __pbn__MatchingRankFes = null;
        private uint? __pbn__MatchingRankFes;

        [global::ProtoBuf.ProtoContract()]
        public partial class StunResult : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public NatMappingType nat_mapping_type { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public NatFilteringType nat_filtering_type { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum NatMappingType
            {
                [global::ProtoBuf.ProtoEnum(Name = @"NM_NONE")]
                NmNone = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"NM_ENDPOINT_INDEPENDENT")]
                NmEndpointIndependent = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"NM_ADDRESS_DEPENDENT")]
                NmAddressDependent = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"NM_ADDRESS_AND_PORT_DEPENDENT")]
                NmAddressAndPortDependent = 3,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum NatFilteringType
            {
                [global::ProtoBuf.ProtoEnum(Name = @"NF_NONE")]
                NfNone = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"NF_ENDPOINT_INDEPENDENT")]
                NfEndpointIndependent = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"NF_ADDRESS_DEPENDENT")]
                NfAddressDependent = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"NF_ADDRESS_AND_PORT_DEPENDENT")]
                NfAddressAndPortDependent = 3,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class OtherPlayerInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"loc_id", IsRequired = true)]
            public string LocId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"pcb_serial", IsRequired = true)]
            public string PcbSerial { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"skill_point_mobile_suit_id", IsRequired = true)]
            public uint SkillPointMobileSuitId { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"pilot_id", IsRequired = true)]
            public uint PilotId { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"rtt", IsRequired = true)]
            public uint Rtt { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"class_id")]
            public uint ClassId
            {
                get => __pbn__ClassId.GetValueOrDefault();
                set => __pbn__ClassId = value;
            }
            public bool ShouldSerializeClassId() => __pbn__ClassId != null;
            public void ResetClassId() => __pbn__ClassId = null;
            private uint? __pbn__ClassId;

            [global::ProtoBuf.ProtoMember(7, Name = @"level_id")]
            public uint LevelId
            {
                get => __pbn__LevelId.GetValueOrDefault();
                set => __pbn__LevelId = value;
            }
            public bool ShouldSerializeLevelId() => __pbn__LevelId != null;
            public void ResetLevelId() => __pbn__LevelId = null;
            private uint? __pbn__LevelId;

            [global::ProtoBuf.ProtoMember(8, Name = @"matching_rank_free")]
            public uint MatchingRankFree
            {
                get => __pbn__MatchingRankFree.GetValueOrDefault();
                set => __pbn__MatchingRankFree = value;
            }
            public bool ShouldSerializeMatchingRankFree() => __pbn__MatchingRankFree != null;
            public void ResetMatchingRankFree() => __pbn__MatchingRankFree = null;
            private uint? __pbn__MatchingRankFree;

            [global::ProtoBuf.ProtoMember(9, Name = @"matching_rank_fes")]
            public uint MatchingRankFes
            {
                get => __pbn__MatchingRankFes.GetValueOrDefault();
                set => __pbn__MatchingRankFes = value;
            }
            public bool ShouldSerializeMatchingRankFes() => __pbn__MatchingRankFes != null;
            public void ResetMatchingRankFes() => __pbn__MatchingRankFes = null;
            private uint? __pbn__MatchingRankFes;

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
//#endregion
