// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

[global::ProtoBuf.ProtoContract()]
public partial class Request0 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
    public MethodType Type { get; set; } = MethodType.MthdRegisterPcb;

    [global::ProtoBuf.ProtoMember(2, Name = @"request_id", IsRequired = true)]
    public string RequestId { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"pcb_serial", IsRequired = true)]
    public string PcbSerial { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"loc_id", IsRequired = true)]
    public string LocId { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"am_id")]
    public uint AmId { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"token", IsRequired = true)]
    public string Token { get; set; }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
