// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Request
{
    [global::ProtoBuf.ProtoMember(1418)]
    public LoadRoom load_room { get; set; }
    
    [global::ProtoBuf.ProtoMember(1419)]
    public RegisterRoom register_room { get; set; }
    
    // 1419
    [global::ProtoBuf.ProtoContract()]
    public partial class RegisterRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pilot_id", IsRequired = true)]
        public uint PilotId { get; set; }
        
        [global::ProtoBuf.ProtoMember(2, Name = @"room_id", IsRequired = true)]
        public uint RoomId { get; set; }
        
        [global::ProtoBuf.ProtoMember(3, Name = @"tag_type", IsRequired = true)]
        public uint TagType { get; set; }

    }
    
    // 1418
    [global::ProtoBuf.ProtoContract()]
    public partial class LoadRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1, Name = @"is_card", IsRequired = true)]
        public uint IsCard { get; set; }
        
        [global::ProtoBuf.ProtoMember(2, Name = @"access_code", IsRequired = true)]
        public string AccessCode { get; set; }
        
        [global::ProtoBuf.ProtoMember(3, Name = @"chip_id", IsRequired = true)]
        public string ChipId { get; set; }
        
        [global::ProtoBuf.ProtoMember(4, Name = @"mucha_country_code", IsRequired = true)]
        public string MuchaCountryCode { get; set; }
        
    }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192