// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Request
{
    // 1201
    [global::ProtoBuf.ProtoContract()]
    public partial class SaveVsmOnResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pilot_id", IsRequired = true)]
        public uint PilotId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session_id", IsRequired = true)]
        public string SessionId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"shuffle_flag", IsRequired = true)]
        public bool ShuffleFlag { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"result", IsRequired = true)]
        public PlayResultGroup Result { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"unfitted_locs")]
        public global::System.Collections.Generic.List<UnfittedLocationGroup> UnfittedLocs { get; } = new();

        [global::ProtoBuf.ProtoMember(6, Name = @"network_report", IsRequired = true)]
        public NetworkReport NetworkReport { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class PlayResultGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"played_at", IsRequired = true)]
            public ulong PlayedAt { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"win_flag", IsRequired = true)]
            public bool WinFlag { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"revenge_num", IsRequired = true)]
            public uint RevengeNum { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"vs_elapsed_time", IsRequired = true)]
            public uint VsElapsedTime { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"stage_id", IsRequired = true)]
            public uint StageId { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"selected_stage_id", IsRequired = true)]
            public uint SelectedStageId { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"mst_mobile_suit_id", IsRequired = true)]
            public uint MstMobileSuitId { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"skill_point_mobile_suit_id", IsRequired = true)]
            public uint SkillPointMobileSuitId { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"result_score", IsRequired = true)]
            public uint ResultScore { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"downed_num", IsRequired = true)]
            public uint DownedNum { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"consecutive_win", IsRequired = true)]
            public uint ConsecutiveWin { get; set; }

            [global::ProtoBuf.ProtoMember(12, Name = @"no_damage_flag", IsRequired = true)]
            public bool NoDamageFlag { get; set; }

            [global::ProtoBuf.ProtoMember(13, Name = @"complete_down_flag", IsRequired = true)]
            public bool CompleteDownFlag { get; set; }

            [global::ProtoBuf.ProtoMember(14, Name = @"perfect_win_flag", IsRequired = true)]
            public bool PerfectWinFlag { get; set; }

            [global::ProtoBuf.ProtoMember(15, Name = @"great_win_flag", IsRequired = true)]
            public bool GreatWinFlag { get; set; }

            [global::ProtoBuf.ProtoMember(16, Name = @"complete_defeat_flag", IsRequired = true)]
            public bool CompleteDefeatFlag { get; set; }

            [global::ProtoBuf.ProtoMember(17, Name = @"level_id", IsRequired = true)]
            public uint LevelId { get; set; }

            [global::ProtoBuf.ProtoMember(18, Name = @"player_level_id", IsRequired = true)]
            public uint PlayerLevelId { get; set; }

            [global::ProtoBuf.ProtoMember(19, Name = @"badge_id", IsRequired = true)]
            public uint PrestigeId { get; set; }

            [global::ProtoBuf.ProtoMember(20, Name = @"level_exp", IsRequired = true)]
            public uint LevelExp { get; set; }

            [global::ProtoBuf.ProtoMember(22, Name = @"gp", IsRequired = true)] //--
            public uint Gp { get; set; }

            [global::ProtoBuf.ProtoMember(23, Name = @"result_order", IsRequired = true)]
            public uint ResultOrder { get; set; }

            [global::ProtoBuf.ProtoMember(24, Name = @"tag_team_id", IsRequired = true)]
            public uint TagTeamId { get; set; }

            [global::ProtoBuf.ProtoMember(25, Name = @"tag_skill_point", IsRequired = true)] //--
            public uint TagSkillPoint { get; set; }

            [global::ProtoBuf.ProtoMember(27, Name = @"guest_nav_id", IsRequired = true)]
            public uint GuestNavId { get; set; }
            [global::ProtoBuf.ProtoMember(28, Name = @"guest_nav_familiarity", IsRequired = true)]
            public uint GuestNavFamiliarity { get; set; }
            [global::ProtoBuf.ProtoMember(29, Name = @"guest_nav_costume_used", IsRequired = true)]
            public uint GuestNavCostumeUsed { get; set; }

            [global::ProtoBuf.ProtoMember(30, Name = @"battle_nav_id", IsRequired = true)] //--
            public uint BattleNavId { get; set; }
            [global::ProtoBuf.ProtoMember(31, Name = @"battle_nav_familiarity", IsRequired = true)] //--
            public uint BattleNavFamiliarity { get; set; }

            [global::ProtoBuf.ProtoMember(32, Name = @"burst_type", IsRequired = true)]
            public uint BurstType { get; set; }

            [global::ProtoBuf.ProtoMember(33, Name = @"ten_consecutive_win_flag", IsRequired = true)]
            public bool TenConsecutiveWinFlag { get; set; }

            [global::ProtoBuf.ProtoMember(34, Name = @"given_damage", IsRequired = true)]
            public uint GivenDamage { get; set; }

            [global::ProtoBuf.ProtoMember(35, Name = @"taken_damage", IsRequired = true)]
            public uint TakenDamage { get; set; }

            [global::ProtoBuf.ProtoMember(36, Name = @"burst", IsRequired = true)]
            public uint Burst { get; set; }

            [global::ProtoBuf.ProtoMember(37, Name = @"overheat", IsRequired = true)]
            public uint Overheat { get; set; }

            [global::ProtoBuf.ProtoMember(38, Name = @"combo_given_damage", IsRequired = true)]
            public uint ComboGivenDamage { get; set; }

            [global::ProtoBuf.ProtoMember(39, Name = @"partner")]
            public AdversaryManGroup Partner { get; set; }

            [global::ProtoBuf.ProtoMember(40, Name = @"foes")]
            public global::System.Collections.Generic.List<AdversaryManGroup> Foes { get; } = new();

            [global::ProtoBuf.ProtoMember(41, Name = @"matching_tag")]
            public MatchingTag MatchingTag { get; set; }

            [global::ProtoBuf.ProtoMember(43, Name = @"room_id", IsRequired = true)]
            public uint RoomId { get; set; }

            [global::ProtoBuf.ProtoMember(44, Name = @"burst_given_damage", IsRequired = true)]
            public uint BurstGivenDamage { get; set; }

            [global::ProtoBuf.ProtoMember(47, Name = @"timer", IsRequired = true)]
            public uint Timer { get; set; }

            [global::ProtoBuf.ProtoMember(48, Name = @"war_situation_flag", IsRequired = true)]
            public bool WarSituationFlag { get; set; }

            [global::ProtoBuf.ProtoMember(49, Name = @"player_battle_log")]
            public global::System.Collections.Generic.List<WarSituationGroup> PlayerBattleLogs { get; } = new();

            [global::ProtoBuf.ProtoMember(50, Name = @"link_num", IsRequired = true)]
            public uint LinkNum { get; set; }

            [global::ProtoBuf.ProtoMember(51, Name = @"cover_num", IsRequired = true)]
            public uint CoverNum { get; set; }

            [global::ProtoBuf.ProtoMember(52, Name = @"guard_num", IsRequired = true)]
            public uint GuardNum { get; set; }

            [global::ProtoBuf.ProtoMember(55, Name = @"ex_burst_xross_num", IsRequired = true)]
            public uint ExBurstXrossNum { get; set; }

            [global::ProtoBuf.ProtoMember(56, Name = @"online_matching_mode", IsRequired = true)]
            public OnlineMatchingMode OnlineMatchingMode { get; set; }

            [global::ProtoBuf.ProtoMember(57, Name = @"class_match_result")]
            public ClassMatchResult class_match_result { get; set; }

            [global::ProtoBuf.ProtoMember(58, Name = @"mobile_user_id")]
            public uint MobileUserId
            {
                get => __pbn__MobileUserId.GetValueOrDefault();
                set => __pbn__MobileUserId = value;
            }
            public bool ShouldSerializeMobileUserId() => __pbn__MobileUserId != null;
            public void ResetMobileUserId() => __pbn__MobileUserId = null;
            private uint? __pbn__MobileUserId;

            [global::ProtoBuf.ProtoMember(59, Name = @"instant_team_flag", IsRequired = true)]
            public bool InstantTeamFlag { get; set; }

            [global::ProtoBuf.ProtoMember(60, Name = @"xross_fes_rule_type")]
            public uint XrossFesRuleType
            {
                get => __pbn__XrossFesRuleType.GetValueOrDefault();
                set => __pbn__XrossFesRuleType = value;
            }
            public bool ShouldSerializeXrossFesRuleType() => __pbn__XrossFesRuleType != null;
            public void ResetXrossFesRuleType() => __pbn__XrossFesRuleType = null;
            private uint? __pbn__XrossFesRuleType;

            [global::ProtoBuf.ProtoMember(61, Name = @"partner_recruit_flag", IsRequired = true)]
            public bool PartnerRecruitFlag { get; set; }

            [global::ProtoBuf.ProtoMember(62, Name = @"time_rental_flag", IsRequired = true)]
            public bool TimeRentalFlag { get; set; }

            [global::ProtoBuf.ProtoMember(63, Name = @"gp_boost_flag")] //--
            public bool GpBoostFlag
            {
                get => __pbn__GpBoostFlag.GetValueOrDefault();
                set => __pbn__GpBoostFlag = value;
            }
            public bool ShouldSerializeGpBoostFlag() => __pbn__GpBoostFlag != null;
            public void ResetGpBoostFlag() => __pbn__GpBoostFlag = null;
            private bool? __pbn__GpBoostFlag;

            [global::ProtoBuf.ProtoMember(64, Name = @"guest_nav_boost_flag")]
            public bool GuestNavBoostFlag
            {
                get => __pbn__GuestNavBoostFlag.GetValueOrDefault();
                set => __pbn__GuestNavBoostFlag = value;
            }
            public bool ShouldSerializeGuestNavBoostFlag() => __pbn__GuestNavBoostFlag != null;
            public void ResetGuestNavBoostFlag() => __pbn__GuestNavBoostFlag = null;
            private bool? __pbn__GuestNavBoostFlag;

            [global::ProtoBuf.ProtoMember(65, Name = @"tag_boost_flag")] //--
            public bool TagBoostFlag
            {
                get => __pbn__TagBoostFlag.GetValueOrDefault();
                set => __pbn__TagBoostFlag = value;
            }
            public bool ShouldSerializeTagBoostFlag() => __pbn__TagBoostFlag != null;
            public void ResetTagBoostFlag() => __pbn__TagBoostFlag = null;
            private bool? __pbn__TagBoostFlag;

            [global::ProtoBuf.ProtoMember(66, Name = @"skin_id", IsRequired = true)]
            public uint SkinId { get; set; }

            [global::ProtoBuf.ProtoMember(67)]
            public ThrowGameInfo throw_game_info { get; set; }

            [global::ProtoBuf.ProtoMember(68, Name = @"sleep_sec")]
            public uint SleepSec
            {
                get => __pbn__SleepSec.GetValueOrDefault();
                set => __pbn__SleepSec = value;
            }
            public bool ShouldSerializeSleepSec() => __pbn__SleepSec != null;
            public void ResetSleepSec() => __pbn__SleepSec = null;
            private uint? __pbn__SleepSec;

            [global::ProtoBuf.ProtoMember(69, Name = @"obtained_badge_point", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
            public int ObtainedScore { get; set; }
            
            [global::ProtoBuf.ProtoMember(70, Name = @"quick_start_info", IsRequired = true)]
            public QuickStartInfo QuickStartInfo { get; set; } = new();

            //[global::ProtoBuf.ProtoMember(71, Name = @"group_tag_point")]
            //public uint GroupTagPoint { get; set; }
            //[global::ProtoBuf.ProtoMember(72, Name = @"group_id")]
            //public uint GroupId { get; set; }

            [global::ProtoBuf.ProtoMember(73, Name = @"overlimit_flag", IsRequired = true)]
            public bool OverlimitFlag { get; set; }
            [global::ProtoBuf.ProtoMember(74, Name = @"overlimit_given_damage", IsRequired = true)]
            public uint OverlimitGivenDamage { get; set; }

            [global::ProtoBuf.ProtoMember(75, Name = @"one_on_one_flag", IsRequired = true)]
            public bool OneOnOneFlag { get; set; }

            // 71 group_tag_point
            // 72 group_id

            [global::ProtoBuf.ProtoContract()]
            public partial class ClassMatchResult : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"class_id_solo", IsRequired = true)]
                public uint ClassIdSolo { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"class_id_team", IsRequired = true)]
                public uint ClassIdTeam { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"before_rate", IsRequired = true)]
                public float BeforeRate { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"after_rate", IsRequired = true)]
                public float AfterRate { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"obtained_rate", IsRequired = true)]
                public float ObtainedRate { get; set; }
                
                [global::ProtoBuf.ProtoMember(6, Name = @"grade_id", IsRequired = true)]
                public uint GradeId { get; set; }
            }

            [global::ProtoBuf.ProtoContract()]
            public partial class ThrowGameInfo : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"cond_1_numbers")]
                public uint[] Cond1Numbers { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"cond_2_numbers")]
                public uint[] Cond2Numbers { get; set; }

            }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
