// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Request
{
    // 1204
    [global::ProtoBuf.ProtoContract()]
    public partial class SaveVstResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session_id", IsRequired = true)]
        public string SessionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"pilot_id", IsRequired = true)]
        public uint PilotId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"player_level_id", IsRequired = true)]
        public uint PlayerLevelId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"prestige_id", IsRequired = true)]
        public uint PrestigeId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"last_mobile_suit_id")]
        public uint LastMobileSuitId
        {
            get => __pbn__LastMobileSuitId.GetValueOrDefault();
            set => __pbn__LastMobileSuitId = value;
        }
        public bool ShouldSerializeLastMobileSuitId() => __pbn__LastMobileSuitId != null;
        public void ResetLastMobileSuitId() => __pbn__LastMobileSuitId = null;
        private uint? __pbn__LastMobileSuitId;

        [global::ProtoBuf.ProtoMember(6, Name = @"last_burst_type")]
        public uint LastBurstType
        {
            get => __pbn__LastBurstType.GetValueOrDefault();
            set => __pbn__LastBurstType = value;
        }
        public bool ShouldSerializeLastBurstType() => __pbn__LastBurstType != null;
        public void ResetLastBurstType() => __pbn__LastBurstType = null;
        private uint? __pbn__LastBurstType;

        [global::ProtoBuf.ProtoMember(7, Name = @"cpu_level")]
        public uint CpuLevel
        {
            get => __pbn__CpuLevel.GetValueOrDefault();
            set => __pbn__CpuLevel = value;
        }
        public bool ShouldSerializeCpuLevel() => __pbn__CpuLevel != null;
        public void ResetCpuLevel() => __pbn__CpuLevel = null;
        private uint? __pbn__CpuLevel;

        [global::ProtoBuf.ProtoMember(8, Name = @"ex_burst_gauge")]
        public uint ExBurstGauge
        {
            get => __pbn__ExBurstGauge.GetValueOrDefault();
            set => __pbn__ExBurstGauge = value;
        }
        public bool ShouldSerializeExBurstGauge() => __pbn__ExBurstGauge != null;
        public void ResetExBurstGauge() => __pbn__ExBurstGauge = null;
        private uint? __pbn__ExBurstGauge;

        [global::ProtoBuf.ProtoMember(9, Name = @"damage_display")]
        public bool DamageDisplay
        {
            get => __pbn__DamageDisplay.GetValueOrDefault();
            set => __pbn__DamageDisplay = value;
        }
        public bool ShouldSerializeDamageDisplay() => __pbn__DamageDisplay != null;
        public void ResetDamageDisplay() => __pbn__DamageDisplay = null;
        private bool? __pbn__DamageDisplay;

        [global::ProtoBuf.ProtoMember(10, Name = @"menu_opened_num", IsRequired = true)]
        public uint MenuOpenedNum { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"change_num", IsRequired = true)]
        public uint ChangeNum { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"change_foe_num", IsRequired = true)]
        public uint ChangeFoeNum { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"result", IsRequired = true)]
        public PlayResultGroup Result { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"cpu_auto_guard")]
        public bool CpuAutoGuard
        {
            get => __pbn__CpuAutoGuard.GetValueOrDefault();
            set => __pbn__CpuAutoGuard = value;
        }
        public bool ShouldSerializeCpuAutoGuard() => __pbn__CpuAutoGuard != null;
        public void ResetCpuAutoGuard() => __pbn__CpuAutoGuard = null;
        private bool? __pbn__CpuAutoGuard;

        [global::ProtoBuf.ProtoMember(15, Name = @"command_guide_display")]
        public uint CommandGuideDisplay { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"training_type")]
        public uint TrainingType
        {
            get => __pbn__TrainingType.GetValueOrDefault();
            set => __pbn__TrainingType = value;
        }
        public bool ShouldSerializeTrainingType() => __pbn__TrainingType != null;
        public void ResetTrainingType() => __pbn__TrainingType = null;
        private uint? __pbn__TrainingType;

        [global::ProtoBuf.ProtoMember(17, Name = @"player_no")]
        public uint PlayerNo
        {
            get => __pbn__PlayerNo.GetValueOrDefault();
            set => __pbn__PlayerNo = value;
        }
        public bool ShouldSerializePlayerNo() => __pbn__PlayerNo != null;
        public void ResetPlayerNo() => __pbn__PlayerNo = null;
        private uint? __pbn__PlayerNo;

        [global::ProtoBuf.ProtoMember(18, Name = @"partner_mobile_suit_id")]
        public uint PartnerMobileSuitId
        {
            get => __pbn__PartnerMobileSuitId.GetValueOrDefault();
            set => __pbn__PartnerMobileSuitId = value;
        }
        public bool ShouldSerializePartnerMobileSuitId() => __pbn__PartnerMobileSuitId != null;
        public void ResetPartnerMobileSuitId() => __pbn__PartnerMobileSuitId = null;
        private uint? __pbn__PartnerMobileSuitId;

        [global::ProtoBuf.ProtoMember(19, Name = @"time_rental_flag", IsRequired = true)]
        public bool TimeRentalFlag { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"quick_start_info", IsRequired = true)]
        public QuickStartInfo QuickStartInfo { get; set; }
        
        [global::ProtoBuf.ProtoMember(21, Name = @"tutorial_flag", IsRequired = true)]
        public bool TutorialFlag { get; set; }
        
        [global::ProtoBuf.ProtoMember(22, Name = @"cpu_hp_auto_regen", IsRequired = true)]
        public uint CpuHpAutoRegen { get; set; }
        [global::ProtoBuf.ProtoMember(23, Name = @"ex_over_limit", IsRequired = true)]
        public uint ExOverLimit { get; set; }
        [global::ProtoBuf.ProtoMember(24, Name = @"quick_fill", IsRequired = true)]
        public uint QuickFill { get; set; }
        [global::ProtoBuf.ProtoMember(25, Name = @"player1_hp_mode", IsRequired = true)]
        public uint Player1HpMode { get; set; }
        
        [global::ProtoBuf.ProtoContract()]
        public partial class PlayResultGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"played_at", IsRequired = true)]
            public ulong PlayedAt { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"continue_num", IsRequired = true)]
            public uint ContinueNum { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"max_damage", IsRequired = true)]
            public uint MaxDamage { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"my_mobile_suit_id", IsRequired = true)]
            public uint MyMobileSuitId { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"my_burst_type", IsRequired = true)]
            public uint MyBurstType { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"enemy_mobile_suit_id", IsRequired = true)]
            public uint EnemyMobileSuitId { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"enemy_burst_type", IsRequired = true)]
            public uint EnemyBurstType { get; set; }

        }
        
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192