// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Request
{
    // 1205
    [global::ProtoBuf.ProtoContract()]
    public partial class SaveVsmToResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pilot_id", IsRequired = true)]
        public uint PilotId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session_id", IsRequired = true)]
        public string SessionId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"shuffle_flag", IsRequired = true)]
        public bool ShuffleFlag { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"result", IsRequired = true)]
        public PlayResultGroup Result { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class PlayResultGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"played_at", IsRequired = true)]
            public ulong PlayedAt { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"loc_id", IsRequired = true)]
            public string LocId { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"tournament_id", IsRequired = true)]
            public uint TournamentId { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"round_num", IsRequired = true)]
            public uint RoundNum { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"round_sequence", IsRequired = true)]
            public uint RoundSequence { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"best_of_two", IsRequired = true)]
            public uint BestOfTwo { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"vs_num", IsRequired = true)]
            public uint VsNum { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"win_flag", IsRequired = true)]
            public bool WinFlag { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"vs_elapsed_time", IsRequired = true)]
            public uint VsElapsedTime { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"stage_id", IsRequired = true)]
            public uint StageId { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"selected_stage_id", IsRequired = true)]
            public uint SelectedStageId { get; set; }

            [global::ProtoBuf.ProtoMember(12, Name = @"mst_mobile_suit_id", IsRequired = true)]
            public uint MstMobileSuitId { get; set; }

            [global::ProtoBuf.ProtoMember(13, Name = @"result_score", IsRequired = true)]
            public uint ResultScore { get; set; }

            [global::ProtoBuf.ProtoMember(14, Name = @"downed_num", IsRequired = true)]
            public uint DownedNum { get; set; }

            [global::ProtoBuf.ProtoMember(15, Name = @"no_damage_flag", IsRequired = true)]
            public bool NoDamageFlag { get; set; }

            [global::ProtoBuf.ProtoMember(16, Name = @"complete_down_flag", IsRequired = true)]
            public bool CompleteDownFlag { get; set; }

            [global::ProtoBuf.ProtoMember(17, Name = @"perfect_win_flag", IsRequired = true)]
            public bool PerfectWinFlag { get; set; }

            [global::ProtoBuf.ProtoMember(18, Name = @"great_win_flag", IsRequired = true)]
            public bool GreatWinFlag { get; set; }

            [global::ProtoBuf.ProtoMember(19, Name = @"complete_defeat_flag", IsRequired = true)]
            public bool CompleteDefeatFlag { get; set; }

            [global::ProtoBuf.ProtoMember(20, Name = @"result_order", IsRequired = true)]
            public uint ResultOrder { get; set; }

            [global::ProtoBuf.ProtoMember(21, Name = @"tag_team_id", IsRequired = true)]
            public uint TagTeamId { get; set; }

            [global::ProtoBuf.ProtoMember(22, Name = @"guest_nav_id", IsRequired = true)]
            public uint GuestNavId { get; set; }
            [global::ProtoBuf.ProtoMember(23, Name = @"guest_nav_familiarity", IsRequired = true)]
            public uint GuestNavFamiliarity { get; set; }
            [global::ProtoBuf.ProtoMember(24, Name = @"guest_nav_costume_used", IsRequired = true)]
            public uint GuestNavCostumeUsed { get; set; }

            //--[global::ProtoBuf.ProtoMember(27, Name = @"battle_nav_id", IsRequired = true)]
            //--public uint BattleNavId { get; set; }
            //--[global::ProtoBuf.ProtoMember(28, Name = @"battle_nav_familiarity", IsRequired = true)]
            //--public uint BattleNavFamiliarity { get; set; }

            [global::ProtoBuf.ProtoMember(29, Name = @"burst_type", IsRequired = true)]
            public uint BurstType { get; set; }

            [global::ProtoBuf.ProtoMember(30, Name = @"given_damage", IsRequired = true)]
            public uint GivenDamage { get; set; }

            [global::ProtoBuf.ProtoMember(31, Name = @"taken_damage", IsRequired = true)]
            public uint TakenDamage { get; set; }

            [global::ProtoBuf.ProtoMember(32, Name = @"burst", IsRequired = true)]
            public uint Burst { get; set; }

            [global::ProtoBuf.ProtoMember(33, Name = @"overheat", IsRequired = true)]
            public uint Overheat { get; set; }

            [global::ProtoBuf.ProtoMember(34, Name = @"combo_given_damage", IsRequired = true)]
            public uint ComboGivenDamage { get; set; }

            [global::ProtoBuf.ProtoMember(35, Name = @"burst_given_damage", IsRequired = true)]
            public uint BurstGivenDamage { get; set; }

            [global::ProtoBuf.ProtoMember(36, Name = @"partner", IsRequired = true)]
            public AdversaryToManGroup Partner { get; set; }

            [global::ProtoBuf.ProtoMember(37, Name = @"foes")]
            public global::System.Collections.Generic.List<AdversaryToManGroup> Foes { get; } = new();

            [global::ProtoBuf.ProtoMember(38, Name = @"player_level_id", IsRequired = true)]
            public uint PlayerLevelId { get; set; }

            [global::ProtoBuf.ProtoMember(39, Name = @"prestige_id", IsRequired = true)] //--
            public uint PrestigeId { get; set; }

            [global::ProtoBuf.ProtoMember(40, Name = @"timer", IsRequired = true)]
            public uint Timer { get; set; }

            [global::ProtoBuf.ProtoMember(41, Name = @"war_situation_flag", IsRequired = true)]
            public bool WarSituationFlag { get; set; }

            [global::ProtoBuf.ProtoMember(42, Name = @"player_battle_log")]
            public global::System.Collections.Generic.List<WarSituationGroup> PlayerBattleLogs { get; } = new();

            [global::ProtoBuf.ProtoMember(43, Name = @"ex_burst_xross_num", IsRequired = true)]
            public uint ExBurstXrossNum { get; set; }

            [global::ProtoBuf.ProtoMember(44, Name = @"skin_id", IsRequired = true)]
            public uint SkinId { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class AdversaryToManGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"pilot_id", IsRequired = true)]
                public uint PilotId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"mst_mobile_suit_id", IsRequired = true)]
                public uint MstMobileSuitId { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"down_num", IsRequired = true)]
                public uint DownNum { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"player_level_id", IsRequired = true)]
                public uint PlayerLevelId { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"badge_id", IsRequired = true)]
                public uint PrestigeId { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"skill_point", IsRequired = true)]
                public uint SkillPoint { get; set; }

                [global::ProtoBuf.ProtoMember(7, Name = @"burst_type", IsRequired = true)]
                public uint BurstType { get; set; }

                [global::ProtoBuf.ProtoMember(8, Name = @"battle_log")]
                public global::System.Collections.Generic.List<WarSituationGroup> BattleLogs { get; } = new();

                [global::ProtoBuf.ProtoMember(9, Name = @"skin_id", IsRequired = true)]
                public uint SkinId { get; set; }

            }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
