// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Request
{
    // 1206
    [global::ProtoBuf.ProtoContract()]
    public partial class SavePracticeResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pilot_id", IsRequired = true)]
        public uint PilotId { get; set; }
        
        [global::ProtoBuf.ProtoMember(2, Name = @"session_id", IsRequired = true)]
        public string SessionId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"result", IsRequired = true)]
        public PlayResultGroup Result { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class PlayResultGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"played_at", IsRequired = true)]
            public ulong PlayedAt { get; set; }
            
            [global::ProtoBuf.ProtoMember(2, Name = @"win_flag", IsRequired = true)]
            public bool WinFlag { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"course_clear_flag", IsRequired = true)]
            public bool CourseClearFlag { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"vs_elapsed_time", IsRequired = true)]
            public uint VsElapsedTime { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"mst_mobile_suit_id", IsRequired = true)]
            public uint MstMobileSuitId { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"skill_point_mobile_suit_id", IsRequired = true)]
            public uint SkillPointMobileSuitId { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"scene_seq", IsRequired = true)]
            public uint SceneSeq { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"scene_difficulty", IsRequired = true)]
            public uint SceneDifficulty { get; set; }
            
            [global::ProtoBuf.ProtoMember(9, Name = @"course_score")]
            public uint CourseScore { get; set; }
            
            [global::ProtoBuf.ProtoMember(10, Name = @"scene_score", IsRequired = true)]
            public uint SceneScore { get; set; }
            
            [global::ProtoBuf.ProtoMember(11, Name = @"total_given_damage")]
            public uint TotalGivenDamage { get; set; }
            
            [global::ProtoBuf.ProtoMember(12, Name = @"total_defeat_num")]
            public uint TotalDefeatNum { get; set; }
            
            [global::ProtoBuf.ProtoMember(13, Name = @"total_ex_burst")]
            public uint TotalExBurst { get; set; }
            
            [global::ProtoBuf.ProtoMember(14, Name = @"total_rocked_on")]
            public uint TotalRockedOn { get; set; }
            
            [global::ProtoBuf.ProtoMember(15, Name = @"total_taken_damage")]
            public uint TotalTakenDamage { get; set; }
            
            [global::ProtoBuf.ProtoMember(16, Name = @"all_s_flag")]
            public bool All_s_flag { get; set; }
            
            [global::ProtoBuf.ProtoMember(17, Name = @"level_id", IsRequired = true)]
            public uint LevelId { get; set; }
            [global::ProtoBuf.ProtoMember(18, Name = @"player_level_id", IsRequired = true)]
            public uint PlayerLevelId { get; set; }
            [global::ProtoBuf.ProtoMember(19, Name = @"level_exp", IsRequired = true)]
            public uint LevelExp { get; set; }
            
            [global::ProtoBuf.ProtoMember(20, Name = @"group_id")]
            public uint GroupId { get; set; }
            
            [global::ProtoBuf.ProtoMember(21, Name = @"guest_nav_id", IsRequired = true)]
            public uint GuestNavId { get; set; }
            [global::ProtoBuf.ProtoMember(22, Name = @"guest_nav_familiarity", IsRequired = true)]
            public uint GuestNavFamiliarity { get; set; }
            [global::ProtoBuf.ProtoMember(23, Name = @"guest_nav_boost_flag", IsRequired = true)]
            public bool GuestNavBoostFlag { get; set; }
            [global::ProtoBuf.ProtoMember(24, Name = @"guest_nav_costume_used", IsRequired = true)]
            public uint GuestNavCostumeUsed { get; set; }
            
            [global::ProtoBuf.ProtoMember(25, Name = @"burst_type", IsRequired = true)]
            public uint BurstType { get; set; }
            
            [global::ProtoBuf.ProtoMember(26, Name = @"partner")]
            public AdversaryCpuGroupPartner Partner { get; set; }
            
            [global::ProtoBuf.ProtoMember(27, Name = @"time_rental_flag", IsRequired = true)]
            public bool TimeRentalFlag { get; set; }
            
            [global::ProtoBuf.ProtoMember(28, Name = @"quick_start_info")]
            public QuickStartInfo QuickStartInfo { get; set; }
            
            [global::ProtoBuf.ProtoContract()]
            public partial class AdversaryCpuGroupPartner : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"pilot_id", IsRequired = true)]
                public uint PilotId { get; set; }
                
                [global::ProtoBuf.ProtoMember(2, Name = @"cpu_flag", IsRequired = true)]
                public bool CpuFlag { get; set; }
                
                [global::ProtoBuf.ProtoMember(3, Name = @"mst_mobile_suit_id", IsRequired = true)]
                public uint MstMobileSuitId { get; set; }
                
                [global::ProtoBuf.ProtoMember(4, Name = @"burst_type", IsRequired = true)]
                public uint BurstType { get; set; }
                
                [global::ProtoBuf.ProtoMember(5, Name = @"player_level_id", IsRequired = true)]
                public uint PlayerLevelId { get; set; }
                
                [global::ProtoBuf.ProtoMember(6, Name = @"class_id", IsRequired = true)]
                public uint ClassId { get; set; }
                
            }
            
        }
        
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192