// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Request
{
    // 1203
    [global::ProtoBuf.ProtoContract()]
    public partial class SaveVscResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pilot_id", IsRequired = true)]
        public uint PilotId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session_id", IsRequired = true)]
        public string SessionId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"result", IsRequired = true)]
        public IbPlayResultGroup Result { get; set; }
        
        [global::ProtoBuf.ProtoContract()]
        public partial class IbPlayResultGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"played_at", IsRequired = true)] // 1
            public ulong PlayedAt { get; set; }
            
            [global::ProtoBuf.ProtoMember(2, Name = @"stage_id", IsRequired = true)]
            public uint StageId { get; set; }
            [global::ProtoBuf.ProtoMember(3, Name = @"phase_id", IsRequired = true)]
            public uint PhaseId { get; set; }
            [global::ProtoBuf.ProtoMember(4, Name = @"phase_type", IsRequired = true)] // battle_type
            public uint PhaseType { get; set; }
            
            [global::ProtoBuf.ProtoMember(5, Name = @"difficulty", IsRequired = true)]
            public uint Difficulty { get; set; }
            
            [global::ProtoBuf.ProtoMember(6, Name = @"win_flag", IsRequired = true)] // 2
            public bool WinFlag { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"vs_elapsed_time", IsRequired = true)] // 4
            public uint VsElapsedTime { get; set; }
            
            [global::ProtoBuf.ProtoMember(8, Name = @"team_cost_before", IsRequired = true)] // before_gauge
            public uint TeamCostBefore { get; set; }
            [global::ProtoBuf.ProtoMember(9, Name = @"team_cost_after", IsRequired = true)] // after_gauge
            public uint TeamCostAfter { get; set; }
            
            [global::ProtoBuf.ProtoMember(10, Name = @"mst_mobile_suit_id", IsRequired = true)] // 6
            public uint MstMobileSuitId { get; set; }
            //[global::ProtoBuf.ProtoMember(10, Name = @"skill_point_mobile_suit_id", IsRequired = true)] // 7
            //public uint SkillPointMobileSuitId { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"scene_id", IsRequired = true)]
            public ulong p11 { get; set; }

            //[global::ProtoBuf.ProtoMember(12, Name = @"course_score")] // 13
            //public uint CourseScore { get; set; }
            [global::ProtoBuf.ProtoMember(12, Name = @"scene_score", IsRequired = true)] // 14
            public uint SceneScore { get; set; }

            // [global::ProtoBuf.ProtoMember(15, Name = @"no_damage_flag", IsRequired = true)]
            // public bool NoDamageFlag { get; set; }
            // [global::ProtoBuf.ProtoMember(16, Name = @"complete_down_flag", IsRequired = true)]
            // public bool CompleteDownFlag { get; set; }
            // [global::ProtoBuf.ProtoMember(17, Name = @"perfect_win_flag", IsRequired = true)]
            // public bool PerfectWinFlag { get; set; }

            [global::ProtoBuf.ProtoMember(13, Name = @"level_id", IsRequired = true)] // 18
            public uint LevelId { get; set; }
            [global::ProtoBuf.ProtoMember(14, Name = @"player_level_id", IsRequired = true)] // 19
            public uint PlayerLevelId { get; set; }

            // [global::ProtoBuf.ProtoMember(22, Name = @"prestige_id", IsRequired = true)] // 20
            // public uint PrestigeId { get; set; }

            [global::ProtoBuf.ProtoMember(15, Name = @"level_exp", IsRequired = true)] // 21
            public uint LevelExp { get; set; }
            
            [global::ProtoBuf.ProtoMember(16, Name = @"guest_nav_id", IsRequired = true)] // 23
            public uint GuestNavId { get; set; }
            [global::ProtoBuf.ProtoMember(17, Name = @"guest_nav_familiarity", IsRequired = true)] // 24
            public uint GuestNavFamiliarity { get; set; }
            [global::ProtoBuf.ProtoMember(18, Name = @"guest_nav_costume_used", IsRequired = true)] // 25
            public uint GuestNavCostumeUsed { get; set; }
            //[global::ProtoBuf.ProtoMember(16, Name = @"battle_nav_id", IsRequired = true)] // 26
            //public uint BattleNavId { get; set; }
            //[global::ProtoBuf.ProtoMember(17, Name = @"battle_nav_familiarity", IsRequired = true)] // 27
            //public uint BattleNavFamiliarity { get; set; }
            
            [global::ProtoBuf.ProtoMember(19, Name = @"group_id")]
            public uint p19 { get; set; }
            
            [global::ProtoBuf.ProtoMember(20, Name = @"burst_type", IsRequired = true)] // ?40
            public int partner_burst_type { get; set; } // 

            //[global::ProtoBuf.ProtoMember(22, Name = @"partner_pilot_id")] // 33
            //public uint PartnerPilotId { get; set; }
            [global::ProtoBuf.ProtoMember(21, Name = @"partner")] // 34
            public GroupPartner Partner { get; set; }
            
            [global::ProtoBuf.ProtoMember(23, Name = @"time_rental_flag", IsRequired = true)] // 46
            public bool TimeRentalFlag { get; set; }
            
            [global::ProtoBuf.ProtoMember(24, Name = @"quick_start_info", IsRequired = true)]
            public QuickStartInfo QuickStartInfo { get; set; } = new();

            [global::ProtoBuf.ProtoMember(25, Name = @"obtained_badge_point", DataFormat= global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
            public int ObtainedBadgePoint { get; set; }

            [global::ProtoBuf.ProtoMember(26, Name = @"one_on_one_flag")]
            public uint p26 { get; set; }
			            
            // [global::ProtoBuf.ProtoMember(36, Name = @"total_wanted_defeat_num", IsRequired = true)]
            // public uint TotalWantedDefeatNum { get; set; }
            // [global::ProtoBuf.ProtoMember(37, Name = @"link_num", IsRequired = true)]
            // public uint LinkNum { get; set; }
            // [global::ProtoBuf.ProtoMember(38, Name = @"cover_num", IsRequired = true)]
            // public uint CoverNum { get; set; }
            // [global::ProtoBuf.ProtoMember(39, Name = @"guard_num", IsRequired = true)]
            // public uint GuardNum { get; set; }
            
            // 22 guest_nav_boost_flag
            
            [global::ProtoBuf.ProtoContract()]
            public partial class GroupPartner : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"pilot_id", IsRequired = true)]
                public uint PilotId { get; set; }
                
                [global::ProtoBuf.ProtoMember(2, Name = @"player_level_id", IsRequired = true)]
                public uint PlayerLevelId { get; set; }
                
                [global::ProtoBuf.ProtoMember(3, Name = @"cpu_flag", IsRequired = true)]
                public uint CpuFlag { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"mst_mobile_suit_id", IsRequired = true)]
                public uint MstMobileSuitId { get; set; }

                // [global::ProtoBuf.ProtoMember(3, Name = @"down_num", IsRequired = true)]
                // public uint DownNum { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"mobile_set_flag", IsRequired = true)]
                public bool MobileSetFlag { get; set; } // IsTriadPartner

                //[global::ProtoBuf.ProtoMember(6, Name = @"armor_level", IsRequired = true)]
                //public uint ArmorLevel { get; set; }
                
                // [global::ProtoBuf.ProtoMember(7, Name = @"shoot_attack_level", IsRequired = true)]
                // public uint ShootAttackLevel { get; set; }
                //
                // [global::ProtoBuf.ProtoMember(8, Name = @"infight_ttack_level", IsRequired = true)]
                // public uint InfightTtackLevel { get; set; }
                //
                // [global::ProtoBuf.ProtoMember(9, Name = @"booster_level", IsRequired = true)]
                // public uint BoosterLevel { get; set; }
                //
                // [global::ProtoBuf.ProtoMember(10, Name = @"ex_gauge_level", IsRequired = true)]
                // public uint ExGaugeLevel { get; set; }
                
                //[global::ProtoBuf.ProtoMember(6, Name = @"ai_level", IsRequired = true)]
                //public uint AiLevel { get; set; }
                
                // [global::ProtoBuf.ProtoMember(12, Name = @"ms_skill1", IsRequired = true)]
                // public uint MsSkill1 { get; set; }
                //
                // [global::ProtoBuf.ProtoMember(13, Name = @"ms_skill2", IsRequired = true)]
                // public uint MsSkill2 { get; set; }

            }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
