// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

//#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Request
{
    [global::ProtoBuf.ProtoMember(1207, Name = @"save_stage_result", IsRequired = true)]
    public SaveStageResult save_stage_result { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public partial class SaveStageResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pilot_id", IsRequired = true)]
        public uint PilotId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session_id", IsRequired = true)]
        public string SessionId { get; set; }
        
		[global::ProtoBuf.ProtoMember(3, Name = @"result", IsRequired = true)]
        public PlayResultGroup PlayResult { get; set; }
		
		[global::ProtoBuf.ProtoContract()]
        public partial class PlayResultGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"played_at", IsRequired = true)]
            public ulong PlayedAt { get; set; }
            
            [global::ProtoBuf.ProtoMember(2, Name = @"difficulty", IsRequired = true)]
            public uint Difficulty { get; set; }
            
            [global::ProtoBuf.ProtoMember(3, Name = @"stage_id", IsRequired = true)]
            public uint StageId { get; set; }
            
            [global::ProtoBuf.ProtoMember(4, Name = @"stage_clear_flag", IsRequired = true)]
            public bool IsCompleted { get; set; }
            
            [global::ProtoBuf.ProtoMember(5, Name = @"stage_clear_time", IsRequired = true)]
            public uint CompletedTime { get; set; } // sec
            
            [global::ProtoBuf.ProtoMember(6, Name = @"stage_clear_score", IsRequired = true)]
            public uint StageScore { get; set; }
            
            [global::ProtoBuf.ProtoMember(7, Name = @"cp_bonus", IsRequired = true)]
            public uint CpBonus { get; set; }
            
            [global::ProtoBuf.ProtoMember(8, Name = @"team_cost_bonus", IsRequired = true)]
            public uint TeamCostBonus { get; set; }
            
            [global::ProtoBuf.ProtoMember(9, Name = @"time_bonus", IsRequired = true)]
            public uint TimeBonus { get; set; }
            
            [global::ProtoBuf.ProtoMember(10, Name = @"phases_score", IsRequired = true)]
            public uint PhasesScore { get; set; }
            
            [global::ProtoBuf.ProtoMember(11, Name = @"elite_win_bonus", IsRequired = true)]
            public uint EliteBonus { get; set; }
            
            [global::ProtoBuf.ProtoMember(12, Name = @"progress", IsRequired = true)]
            public uint CompletedPhaseCount { get; set; }
            
            [global::ProtoBuf.ProtoMember(13, Name = @"normal_win_num", IsRequired = true)]
            public uint NormalBattleCount { get; set; }
            [global::ProtoBuf.ProtoMember(14, Name = @"elite_win_num", IsRequired = true)]
            public uint EliteBattleCount { get; set; }
            [global::ProtoBuf.ProtoMember(15, Name = @"boss_win_num", IsRequired = true)]
            public uint BossBattleCount { get; set; }
            
            [global::ProtoBuf.ProtoMember(16, Name = @"team_cost_on_start", IsRequired = true)]
            public uint TeamCostOnStart { get; set; }
            [global::ProtoBuf.ProtoMember(17, Name = @"team_cost_curr", IsRequired = true)]
            public uint TeamCostCurr { get; set; }
            
            [global::ProtoBuf.ProtoMember(18, Name = @"final_stage_clear_flag", IsRequired = true)]
            public uint p18 { get; set; } // == p4
            [global::ProtoBuf.ProtoMember(19, Name = @"total_clear_time", IsRequired = true)]
            public uint p19 { get; set; } // == p5
            [global::ProtoBuf.ProtoMember(20, Name = @"total_clear_score", IsRequired = true)]
            public uint p20 { get; set; } // == p6
            
            [global::ProtoBuf.ProtoMember(21, Name = @"time_rental_flag", IsRequired = true)]
            public uint TimeRentalFlag { get; set; }
            
            [global::ProtoBuf.ProtoMember(22, Name = @"mst_mobile_suit_id", IsRequired = true)]
            public uint MsId { get; set; }
            
            [global::ProtoBuf.ProtoMember(23, Name = @"partner_mobile_suit_id", IsRequired = true)]
            public uint PartnerMsId { get; set; }
            
            [global::ProtoBuf.ProtoMember(24, Name = @"partner_pilot_id", IsRequired = true)]
            public uint PartnerId { get; set; }
            
            [global::ProtoBuf.ProtoMember(25, Name = @"cpu_flag", IsRequired = true)]
            public uint PartnerIsCpu { get; set; }
            
            [global::ProtoBuf.ProtoMember(26, Name = @"save_data_info")]
            public CompletedResultGroup CompletedResult { get; set; }
            
            [global::ProtoBuf.ProtoContract()]
            public partial class CompletedResultGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
                
                [global::ProtoBuf.ProtoMember(1, Name = @"pattern_id", IsRequired = true)]
                public uint PatternId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"difficulty", IsRequired = true)]
                public uint Difficulty { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"stage_id", IsRequired = true)]
                public uint StageId { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"boss_id_1", IsRequired = true)]
                public uint Boss1 { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"boss_id_2", IsRequired = true)]
                public uint Boss2 { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"team_cost_on_start", IsRequired = true)]
                public uint TeamCostOnStart { get; set; }
                
                [global::ProtoBuf.ProtoMember(7, Name = @"custom_chip_ids", IsRequired = true)]
                public uint[] Chips { get; set; }  // 芯片ids
            }

        }
    }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
//#endregion
