// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

//#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Request
{
    // 1203
    public partial class SaveVscResult : global::ProtoBuf.IExtensible
    {
        //[global::ProtoBuf.ProtoMember(3, Name = @"result", IsRequired = true)]
        //public PlayResultGroup Result { get; set; } // ob

        [global::ProtoBuf.ProtoContract()]
        public partial class PlayResultGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"played_at", IsRequired = true)]
            public ulong PlayedAt { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"win_flag", IsRequired = true)]
            public bool WinFlag { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"course_clear_flag")]
            public bool CourseClearFlag
            {
                get => __pbn__CourseClearFlag.GetValueOrDefault();
                set => __pbn__CourseClearFlag = value;
            }
            public bool ShouldSerializeCourseClearFlag() => __pbn__CourseClearFlag != null;
            public void ResetCourseClearFlag() => __pbn__CourseClearFlag = null;
            private bool? __pbn__CourseClearFlag;

            [global::ProtoBuf.ProtoMember(4, Name = @"vs_elapsed_time", IsRequired = true)]
            public uint VsElapsedTime { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"course_clear_time")]
            public uint CourseClearTime
            {
                get => __pbn__CourseClearTime.GetValueOrDefault();
                set => __pbn__CourseClearTime = value;
            }
            public bool ShouldSerializeCourseClearTime() => __pbn__CourseClearTime != null;
            public void ResetCourseClearTime() => __pbn__CourseClearTime = null;
            private uint? __pbn__CourseClearTime;

            [global::ProtoBuf.ProtoMember(6, Name = @"mst_mobile_suit_id", IsRequired = true)]
            public uint MstMobileSuitId { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"skill_point_mobile_suit_id", IsRequired = true)]
            public uint SkillPointMobileSuitId { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"course_id", IsRequired = true)]
            public uint CourseId { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"scene_seq", IsRequired = true)]
            public uint SceneSeq { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"scene_id", IsRequired = true)]
            public uint SceneId { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"scene_type", IsRequired = true)]
            public uint SceneType { get; set; }

            [global::ProtoBuf.ProtoMember(12, Name = @"course_category", IsRequired = true)]
            public uint CourseCategory { get; set; }

            [global::ProtoBuf.ProtoMember(13, Name = @"course_score")]
            public uint CourseScore
            {
                get => __pbn__CourseScore.GetValueOrDefault();
                set => __pbn__CourseScore = value;
            }
            public bool ShouldSerializeCourseScore() => __pbn__CourseScore != null;
            public void ResetCourseScore() => __pbn__CourseScore = null;
            private uint? __pbn__CourseScore;

            [global::ProtoBuf.ProtoMember(14, Name = @"scene_score", IsRequired = true)]
            public uint SceneScore { get; set; }

            [global::ProtoBuf.ProtoMember(15, Name = @"no_damage_flag", IsRequired = true)]
            public bool NoDamageFlag { get; set; }

            [global::ProtoBuf.ProtoMember(16, Name = @"complete_down_flag", IsRequired = true)]
            public bool CompleteDownFlag { get; set; }

            [global::ProtoBuf.ProtoMember(17, Name = @"perfect_win_flag", IsRequired = true)]
            public bool PerfectWinFlag { get; set; }

            [global::ProtoBuf.ProtoMember(18, Name = @"level_id", IsRequired = true)]
            public uint LevelId { get; set; }
            [global::ProtoBuf.ProtoMember(19, Name = @"player_level_id", IsRequired = true)]
            public uint PlayerLevelId { get; set; }

            [global::ProtoBuf.ProtoMember(20, Name = @"prestige_id", IsRequired = true)]
            public uint PrestigeId { get; set; }

            [global::ProtoBuf.ProtoMember(21, Name = @"level_exp", IsRequired = true)]
            public uint LevelExp { get; set; }

            [global::ProtoBuf.ProtoMember(22, Name = @"gp", IsRequired = true)]
            public uint Gp { get; set; }

            [global::ProtoBuf.ProtoMember(23, Name = @"guest_nav_id", IsRequired = true)]
            public uint GuestNavId { get; set; }

            [global::ProtoBuf.ProtoMember(24, Name = @"guest_nav_familiarity", IsRequired = true)]
            public uint GuestNavFamiliarity { get; set; }

            [global::ProtoBuf.ProtoMember(25, Name = @"guest_nav_costume_used", IsRequired = true)]
            public uint GuestNavCostumeUsed { get; set; }

            [global::ProtoBuf.ProtoMember(26, Name = @"battle_nav_id", IsRequired = true)]
            public uint BattleNavId { get; set; }

            [global::ProtoBuf.ProtoMember(27, Name = @"battle_nav_familiarity", IsRequired = true)]
            public uint BattleNavFamiliarity { get; set; }

            [global::ProtoBuf.ProtoMember(28, Name = @"tag_team_id", IsRequired = true)]
            public uint TagTeamId { get; set; }

            [global::ProtoBuf.ProtoMember(29, Name = @"tag_skill_point", IsRequired = true)]
            public uint TagSkillPoint { get; set; }

            [global::ProtoBuf.ProtoMember(30, Name = @"burst_type", IsRequired = true)]
            public uint BurstType { get; set; }

            [global::ProtoBuf.ProtoMember(31, Name = @"released_ribbon_id")]
            public uint[] ReleasedRibbonIds { get; set; }

            [global::ProtoBuf.ProtoMember(32, Name = @"released_course_id")]
            public uint[] ReleasedCourseIds { get; set; }

            [global::ProtoBuf.ProtoMember(33, Name = @"partner_pilot_id", IsRequired = true)]
            public uint PartnerPilotId { get; set; }

            [global::ProtoBuf.ProtoMember(34, Name = @"partner")]
            public AdversaryCpuGroupPartner Partner { get; set; }

            [global::ProtoBuf.ProtoMember(35, Name = @"foes")]
            public global::System.Collections.Generic.List<AdversaryCpuGroupFoe> Foes { get; } = new global::System.Collections.Generic.List<AdversaryCpuGroupFoe>();

            [global::ProtoBuf.ProtoMember(36, Name = @"total_wanted_defeat_num", IsRequired = true)]
            public uint TotalWantedDefeatNum { get; set; }

            [global::ProtoBuf.ProtoMember(37, Name = @"link_num", IsRequired = true)]
            public uint LinkNum { get; set; }

            [global::ProtoBuf.ProtoMember(38, Name = @"cover_num", IsRequired = true)]
            public uint CoverNum { get; set; }

            [global::ProtoBuf.ProtoMember(39, Name = @"guard_num", IsRequired = true)]
            public uint GuardNum { get; set; }

            [global::ProtoBuf.ProtoMember(40, Name = @"burst", IsRequired = true)]
            public uint Burst { get; set; }

            [global::ProtoBuf.ProtoMember(41, Name = @"cpu_not_proceed")]
            public bool CpuNotProceed
            {
                get => __pbn__CpuNotProceed.GetValueOrDefault();
                set => __pbn__CpuNotProceed = value;
            }
            public bool ShouldSerializeCpuNotProceed() => __pbn__CpuNotProceed != null;
            public void ResetCpuNotProceed() => __pbn__CpuNotProceed = null;
            private bool? __pbn__CpuNotProceed;

            [global::ProtoBuf.ProtoMember(42, Name = @"cost_skip_flag")]
            public bool CostSkipFlag
            {
                get => __pbn__CostSkipFlag.GetValueOrDefault();
                set => __pbn__CostSkipFlag = value;
            }
            public bool ShouldSerializeCostSkipFlag() => __pbn__CostSkipFlag != null;
            public void ResetCostSkipFlag() => __pbn__CostSkipFlag = null;
            private bool? __pbn__CostSkipFlag;

            [global::ProtoBuf.ProtoMember(43, Name = @"gp_boost_flag")]
            public bool GpBoostFlag
            {
                get => __pbn__GpBoostFlag.GetValueOrDefault();
                set => __pbn__GpBoostFlag = value;
            }
            public bool ShouldSerializeGpBoostFlag() => __pbn__GpBoostFlag != null;
            public void ResetGpBoostFlag() => __pbn__GpBoostFlag = null;
            private bool? __pbn__GpBoostFlag;

            [global::ProtoBuf.ProtoMember(44, Name = @"guest_nav_boost_flag")]
            public bool GuestNavBoostFlag
            {
                get => __pbn__GuestNavBoostFlag.GetValueOrDefault();
                set => __pbn__GuestNavBoostFlag = value;
            }
            public bool ShouldSerializeGuestNavBoostFlag() => __pbn__GuestNavBoostFlag != null;
            public void ResetGuestNavBoostFlag() => __pbn__GuestNavBoostFlag = null;
            private bool? __pbn__GuestNavBoostFlag;

            [global::ProtoBuf.ProtoMember(45, Name = @"tag_boost_flag")]
            public bool TagBoostFlag
            {
                get => __pbn__TagBoostFlag.GetValueOrDefault();
                set => __pbn__TagBoostFlag = value;
            }
            public bool ShouldSerializeTagBoostFlag() => __pbn__TagBoostFlag != null;
            public void ResetTagBoostFlag() => __pbn__TagBoostFlag = null;
            private bool? __pbn__TagBoostFlag;

            [global::ProtoBuf.ProtoMember(46, Name = @"time_rental_flag", IsRequired = true)]
            public bool TimeRentalFlag { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class AdversaryCpuGroupPartner : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"pilot_id", IsRequired = true)]
                public uint PilotId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"cpu_flag", IsRequired = true)]
                public uint CpuFlag { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"mst_mobile_suit_id", IsRequired = true)]
                public uint MstMobileSuitId { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"down_num", IsRequired = true)]
                public uint DownNum { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"mobile_set_flag", IsRequired = true)]
                public bool MobileSetFlag { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"armor_level", IsRequired = true)]
                public uint ArmorLevel { get; set; }

                [global::ProtoBuf.ProtoMember(7, Name = @"shoot_attack_level", IsRequired = true)]
                public uint ShootAttackLevel { get; set; }

                [global::ProtoBuf.ProtoMember(8, Name = @"infight_ttack_level", IsRequired = true)]
                public uint InfightTtackLevel { get; set; }

                [global::ProtoBuf.ProtoMember(9, Name = @"booster_level", IsRequired = true)]
                public uint BoosterLevel { get; set; }

                [global::ProtoBuf.ProtoMember(10, Name = @"ex_gauge_level", IsRequired = true)]
                public uint ExGaugeLevel { get; set; }

                [global::ProtoBuf.ProtoMember(11, Name = @"ai_level", IsRequired = true)]
                public uint AiLevel { get; set; }

                [global::ProtoBuf.ProtoMember(12, Name = @"ms_skill1", IsRequired = true)]
                public uint MsSkill1 { get; set; }

                [global::ProtoBuf.ProtoMember(13, Name = @"ms_skill2", IsRequired = true)]
                public uint MsSkill2 { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class AdversaryCpuGroupFoe : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"mst_mobile_suit_id", IsRequired = true)]
                public uint MstMobileSuitId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"wanted_ms_flag", IsRequired = true)]
                public uint WantedMsFlag { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"target_ms_flag", IsRequired = true)]
                public uint TargetMsFlag { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"down_num", IsRequired = true)]
                public uint DownNum { get; set; }

            }

        }

    }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
//#endregion
