// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

[global::ProtoBuf.ProtoContract()]
public partial class MatchingTag : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
    public uint Id { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"tag_name", IsRequired = true)]
    public string TagName { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"tag_type", IsRequired = true)] // 3
    public uint TagType { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"matching_type", IsRequired = true)] // 4
    public uint MatchingType { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"end_date", IsRequired = true)]
    public ulong EndDate { get; set; }
    
    [global::ProtoBuf.ProtoMember(6, Name = @"matching_attribute", IsRequired = true)] // 6
    public uint MatchingAttribute { get; set; }

    // [global::ProtoBuf.ProtoMember(5, Name = @"tag_matching_num")] // 5
    // public uint TagMatchingNum
    // {
    //     get => __pbn__TagMatchingNum.GetValueOrDefault();
    //     set => __pbn__TagMatchingNum = value;
    // }
    // public bool ShouldSerializeTagMatchingNum() => __pbn__TagMatchingNum != null;
    // public void ResetTagMatchingNum() => __pbn__TagMatchingNum = null;
    // private uint? __pbn__TagMatchingNum;

    [global::ProtoBuf.ProtoMember(7, Name = @"selectable_ms_id")]
    public uint[] SelectableMsIds { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"rule_type")] // 8
    public uint RuleType
    {
        get => __pbn__RuleType.GetValueOrDefault();
        set => __pbn__RuleType = value;
    }
    public bool ShouldSerializeRuleType() => __pbn__RuleType != null;
    public void ResetRuleType() => __pbn__RuleType = null;
    private uint? __pbn__RuleType;

    [global::ProtoBuf.ProtoMember(9, Name = @"revenge_flag", IsRequired = true)]
    public bool RevengeFlag { get; set; }
    
    [global::ProtoBuf.ProtoMember(10, Name = @"timer", IsRequired = true)]
    public uint Timer { get; set; }
    
    [global::ProtoBuf.ProtoMember(11, Name = @"world_id", IsRequired = true)]
    public uint WorldId { get; set; }
    
    [global::ProtoBuf.ProtoMember(12, Name = @"fes_rule_type")]
    public uint FesRuleType { get; set; }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192