// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

[global::ProtoBuf.ProtoContract()]
public enum MethodType
{
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_REGISTER_PCB")]
    MthdRegisterPcb = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_REGISTER_PCB_ACK")]
    MthdRegisterPcbAck = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_INSIDE_DATA")]
    MthdSaveInsideData = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_GAME_DATA")]
    MthdLoadGameData = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_RANK_MATCH")]
    MthdLoadRankMatch = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_CLASS_MATCH")]
    MthdLoadClassMatch = 6,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_PRE_LOAD_CARD")]
    MthdPreLoadCard = 100,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_CARD")]
    MthdLoadCard = 101,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_REGISTER_CARD")]
    MthdRegisterCard = 102,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_VSM_RESULT")]
    MthdSaveVsmResult = 200,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_VSM_ON_RESULT")]
    MthdSaveVsmOnResult = 201,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_VSC_RESULT")]
    MthdSaveVscResult = 203,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_VST_RESULT")]
    MthdSaveVstResult = 204,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_VSM_TO_RESULT")]
    MthdSaveVsmToResult = 205,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_PRACTICE_RESULT")] // 练习记录
    MthdSavePracticeResult = 206,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_STAGE_RESULT")] // ib人机stage大关卡完成时
    MthdSaveStageResult = 207,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_CHARGE")]
    MthdSaveCharge = 210,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_MEDAL")]
    MthdSaveMedal = 211,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_BATTLE_LOG")]
    MthdSaveBattleLog = 220,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_BATTLE_LOG_ON")]
    MthdSaveBattleLogOn = 221,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_USER_PLAY_RESEARCH_DATA")]
    MthdSaveUserPlayResearchData = 223,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_RESULT_CAPTURE")]
    MthdSaveResultCapture = 224,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_FAILED_BATTLE_LOG_ON")]
    MthdSaveFailedBattleLogOn = 225,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_CHECK_COMMUNICATION")]
    MthdCheckCommunication = 300,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_ACCESS_CODE")]
    MthdLoadAccessCode = 303,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_USE_P_COIN_TICKET")]
    MthdUsePCoinTicket = 305,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_REGISTER_OPTION")]
    MthdRegisterOption = 306,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_SPOT_INFO")]
    MthdLoadSpotInfo = 400,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_RANKING")]
    MthdLoadRanking = 401,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_CHECK_TELOP")]
    MthdCheckTelop = 402,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_TELOP")]
    MthdLoadTelop = 403,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_CHECK_MOVIE_RELEASE")]
    MthdCheckMovieRelease = 404,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_SPOT_URL")]
    MthdLoadSpotUrl = 405,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_REPLAY_CARD")]
    MthdLoadReplayCard = 406,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_PRE_SAVE_REPLAY")]
    MthdPreSaveReplay = 407,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_MEETING_CARD")]
    MthdLoadMeetingCard = 409,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_TOURNAMENT_RESULT")]
    MthdSaveTournamentResult = 410,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_BLACK_LIST")]
    MthdLoadBlackList = 416,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_START_TOURNAMENT")]
    MthdStartTournament = 417,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_LOAD_ROOM")]
    MthdLoadRoom = 418,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_REGISTER_ROOM")]
    MthdRegisterRoom = 419,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_PING")]
    MthdPing = 500,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_CHECK_TIME")]
    MthdCheckTime = 501,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_SAVE_LOG")]
    MthdSaveLog = 502,
    [global::ProtoBuf.ProtoEnum(Name = @"MTHD_CHECK_RESOURCE_DATA")]
    MthdCheckResourceData = 503,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192