// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

[global::ProtoBuf.ProtoContract()]
public partial class QuickStartInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    // 0=店外 1=混战 2=活动Fes 3=店内 4=自定义对战 5=练习模式 6=街机模式 7=训练场
    [global::ProtoBuf.ProtoMember(1, Name = @"game_mode", IsRequired = true)]
    public uint GameMode { get; set; }
    
    [global::ProtoBuf.ProtoMember(2, Name = @"rule_type", IsRequired = true)]
    public uint RuleType { get; set; }
	
	// 0=单人 1=组队
    [global::ProtoBuf.ProtoMember(3, Name = @"team_type", IsRequired = true)]
    public uint TeamType { get; set; }
    
    [global::ProtoBuf.ProtoMember(4, Name = @"mst_mobile_suit_id_0", IsRequired = true)]
    public uint MstMobileSuitId { get; set; }            
    [global::ProtoBuf.ProtoMember(5, Name = @"burst_type_0", IsRequired = true)]
    public uint BurstType { get; set; }
                
    [global::ProtoBuf.ProtoMember(6, Name = @"mst_mobile_suit_id_1", IsRequired = true)]
    public uint PartnerMobileSuitId { get; set; }
    [global::ProtoBuf.ProtoMember(7, Name = @"burst_type_1", IsRequired = true)]
    public uint PartnerBurstType { get; set; }
    
    [global::ProtoBuf.ProtoMember(8, Name = @"stage_id", IsRequired = true)]
    public uint BattleStageId { get; set; }
    
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192