// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

[global::ProtoBuf.ProtoContract()]
public partial class TagTeamGroup : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
    public uint Id { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
    public string Name { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"partner_id", IsRequired = true)]
    public uint PartnerId { get; set; }
    
    [global::ProtoBuf.ProtoMember(13, Name = @"tag_status", IsRequired = true)]
    public uint TagStatus { get; set; }
    
    [global::ProtoBuf.ProtoMember(14, Name = @"group_tag_point", IsRequired = true)]
    public uint GroupTagPoint { get; set; }
    
    [global::ProtoBuf.ProtoMember(15, Name = @"partner_player_level_id")]
    public uint PartnerPlayerLevelId { get; set; }
    [global::ProtoBuf.ProtoMember(16, Name = @"partner_badge_id")]
    public uint PartnerBadgeId { get; set; }
    [global::ProtoBuf.ProtoMember(17, Name = @"partner_class_id")]
    public uint PartnerClassId { get; set; }
    [global::ProtoBuf.ProtoMember(18, Name = @"partner_grade_id")]
    public uint PartnerGradeId { get; set; }
    [global::ProtoBuf.ProtoMember(19, Name = @"partner_name", IsRequired = true)]
    public string PartnerName { get; set; } = "";


    [global::ProtoBuf.ProtoMember(10004, Name = @"background_parts_id", IsRequired = true)] // 4
    public uint BackgroundPartsId { get; set; }
    [global::ProtoBuf.ProtoMember(10005, Name = @"effect_id", IsRequired = true)] // 5
    public uint EffectId { get; set; }
    [global::ProtoBuf.ProtoMember(10006, Name = @"emblem_id", IsRequired = true)] // 6
    public uint EmblemId { get; set; }
    [global::ProtoBuf.ProtoMember(10007, Name = @"skill_point", IsRequired = true)] // 7
    public uint SkillPoint { get; set; }
    [global::ProtoBuf.ProtoMember(10008, Name = @"skill_point_boost", IsRequired = true)] // 8
    public uint SkillPointBoost { get; set; }
    [global::ProtoBuf.ProtoMember(10010, Name = @"bgm_id", IsRequired = true)] // 10
    public uint BgmId { get; set; }
    [global::ProtoBuf.ProtoMember(10011, Name = @"name_color_id", IsRequired = true)] // 11
    public uint NameColorId { get; set; }
    [global::ProtoBuf.ProtoMember(10012, Name = @"boost_remains", IsRequired = true)] // 12
    public uint BoostRemains { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192