// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

//#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Response2
{
    [global::ProtoBuf.ProtoContract()]
    public partial class LoadCard : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public PilotDataGroup pilot_data_group { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public MobileUserGroup mobile_user_group { get; set; }
        
        [global::ProtoBuf.ProtoContract()]
        public partial class PilotDataGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"reward_ms_id")]
            public uint[] RewardMsIds { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"ms_skills")]
            public global::System.Collections.Generic.List<MSSkillGroup> MsSkills { get; } = new();
            
            //[global::ProtoBuf.ProtoMember(13, Name = @"tag_teams")] // 3
            //public global::System.Collections.Generic.List<TagTeamGroup2> TagTeams { get; } = new();

            //[global::ProtoBuf.ProtoMember(50, Name = @"cpu_scenes")] // 4
            //public global::System.Collections.Generic.List<CpuSceneData> CpuScenes { get; } = new();

            //[global::ProtoBuf.ProtoMember(51, Name = @"cpu_ribbons")] // 5
            //public uint[] CpuRibbons { get; set; }

            //[global::ProtoBuf.ProtoMember(10006, Name = @"total_triad_score", IsRequired = true)] // 6
            //public uint TotalTriadScore { get; set; }

            [global::ProtoBuf.ProtoMember(17, Name = @"total_triad_wanted_defeat_num", IsRequired = true)]
            public uint TotalTriadWantedDefeatNum { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"training", IsRequired = true)]
            public TrainingSettingGroup Training { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"total_triad_scene_play_num", IsRequired = true)]
            public uint TotalTriadScenePlayNum { get; set; }

            //[global::ProtoBuf.ProtoMember(10)]
            //public PilotClassMatch pilot_class_match { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"last_obtained_score", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
            //[global::ProtoBuf.ProtoMember(11, Name = @"last_obtained_score")]
            public int LastObtainedScore { get; set; }

            [global::ProtoBuf.ProtoMember(12, Name = @"license_tracker_score", IsRequired = true)]
            public uint LicenseTrackerScore { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"practice_info", IsRequired = true)]
            public PracticeGroup PracticeInfo { get; set; } = new();
            [global::ProtoBuf.ProtoMember(6, Name = "high_score_info")]
			public global::System.Collections.Generic.List<HighScoreInfo> HighScoreInfos { get; } = new();
            


            [global::ProtoBuf.ProtoContract()]
            public partial class MSSkillGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"mst_mobile_suit_id", IsRequired = true)]
                public uint MstMobileSuitId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"ms_used_num", IsRequired = true)]
                public uint MsUsedNum { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"costume_id", IsRequired = true)]
                public uint CostumeId { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"triad_buddy_point", IsRequired = true)]
                public uint TriadBuddyPoint { get; set; }
                
            }

            [global::ProtoBuf.ProtoContract()]
            public partial class CpuSceneData : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"course_id", IsRequired = true)]
                public uint CourseId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"released_at", IsRequired = true)]
                public ulong ReleasedAt { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"total_play_num", IsRequired = true)]
                public uint TotalPlayNum { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"total_clear_num", IsRequired = true)]
                public uint TotalClearNum { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"highscore", IsRequired = true)]
                public uint Highscore { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class TrainingSettingGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"mst_mobile_suit_id", IsRequired = true)]
                public uint MstMobileSuitId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"burst_type", IsRequired = true)]
                public uint BurstType { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"cpu_level", IsRequired = true)]
                public uint CpuLevel { get; set; } = 0; // 0=stop;

                [global::ProtoBuf.ProtoMember(4, Name = @"ex_burst_gauge", IsRequired = true)]
                public uint ExBurstGauge { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"damage_display", IsRequired = true)]
                public bool DamageDisplay { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"cpu_auto_guard", IsRequired = true)]
                public bool CpuAutoGuard { get; set; }

                [global::ProtoBuf.ProtoMember(7, Name = @"command_guide_display", IsRequired = true)]
                public uint CommandGuideDisplay { get; set; } // 0=off; 1=键位; 2=操作名;
                
                [global::ProtoBuf.ProtoMember(8, Name = @"player1_hp_mode")] // armor
                public uint Player1HpMode { get; set; } = 0;
                
                [global::ProtoBuf.ProtoMember(9, Name = @"cpu_hp_auto_regen")] // cpu_auto_heal
                public uint CpuHpAutoRegen { get; set; } = 0;
                
                [global::ProtoBuf.ProtoMember(10, Name = @"ex_over_limit")]
                public uint ExOverLimit { get; set; } = 0;
                
                [global::ProtoBuf.ProtoMember(11, Name = @"quick_fill")] // fast_reload
                public uint QuickFill { get; set; } = 0;
            }

            #region // PilotClassMatch
            // [global::ProtoBuf.ProtoContract()]
            // public partial class PilotClassMatch : global::ProtoBuf.IExtensible
            // {
            //     private global::ProtoBuf.IExtension __pbn__extensionData;
            //     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            //         => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            //
            //     [global::ProtoBuf.ProtoMember(1, Name = @"pilot_class_match_solo", IsRequired = true)]
            //     public PilotClassMatchInfo PilotClassMatchSolo { get; set; }
            //
            //     [global::ProtoBuf.ProtoMember(2, Name = @"pilot_class_match_team", IsRequired = true)]
            //     public PilotClassMatchInfo PilotClassMatchTeam { get; set; }
            //
            //     [global::ProtoBuf.ProtoContract()]
            //     public partial class PilotClassMatchInfo : global::ProtoBuf.IExtensible
            //     {
            //         private global::ProtoBuf.IExtension __pbn__extensionData;
            //         global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            //             => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            //
            //         [global::ProtoBuf.ProtoMember(1, Name = @"class_id", IsRequired = true)]
            //         public uint ClassId { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(2, Name = @"rate", IsRequired = true)]
            //         public float Rate { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(3, Name = @"max_position", IsRequired = true)]
            //         public uint MaxPosition { get; set; }
            //
            //     }
            //
            // }
            #endregion // PilotClassMatch
            
            [global::ProtoBuf.ProtoContract()]
            public partial class PracticeGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = "highscore_scene_1", IsRequired = true)]
				public uint HighscoreScene1 { get; set; }

				[global::ProtoBuf.ProtoMember(2, Name = "highscore_scene_2", IsRequired = true)]
				public uint HighscoreScene2 { get; set; }

				[global::ProtoBuf.ProtoMember(3, Name = "highscore_scene_3", IsRequired = true)]
				public uint HighscoreScene3 { get; set; }

				[global::ProtoBuf.ProtoMember(4, Name = "highscore_scene_4", IsRequired = true)]
				public uint HighscoreScene4 { get; set; }

				[global::ProtoBuf.ProtoMember(5, Name = "highscore_scene_5", IsRequired = true)]
				public uint HighscoreScene5 { get; set; }

				[global::ProtoBuf.ProtoMember(6, Name = "highscore_scene_6", IsRequired = true)]
				public uint HighscoreScene6 { get; set; }

				[global::ProtoBuf.ProtoMember(7, Name = "course_score", IsRequired = true)]
				public uint CourseScore { get; set; }

				[global::ProtoBuf.ProtoMember(8, Name = "give_damage", IsRequired = true)]
				public uint GiveDamage { get; set; }

				[global::ProtoBuf.ProtoMember(9, Name = "defeat_num", IsRequired = true)]
				public uint DefeatNum { get; set; }

				[global::ProtoBuf.ProtoMember(10, Name = "ex_burst", IsRequired = true)]
				public uint ExBurst { get; set; }

				[global::ProtoBuf.ProtoMember(11, Name = "rocked_on_num", IsRequired = true)]
				public uint RockedOnNum { get; set; }

				[global::ProtoBuf.ProtoMember(12, Name = "taken_damage", IsRequired = true)]
				public uint TakenDamage { get; set; }

				[global::ProtoBuf.ProtoMember(13, Name = "all_s_flag", IsRequired = true)]
				public bool AllSFlag { get; set; }
            }
            
            [global::ProtoBuf.ProtoContract()]
            public partial class HighScoreInfo : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = "difficulty", IsRequired = true)]
				public uint Difficulty { get; set; }

				[global::ProtoBuf.ProtoMember(2, Name = "clear_time_1", IsRequired = true)]
				public uint ClearTime1 { get; set; }

				[global::ProtoBuf.ProtoMember(3, Name = "clear_score_1", IsRequired = true)]
				public uint ClearScore1 { get; set; }

				[global::ProtoBuf.ProtoMember(4, Name = "clear_time_2", IsRequired = true)]
				public uint ClearTime2 { get; set; }

				[global::ProtoBuf.ProtoMember(5, Name = "clear_score_2", IsRequired = true)]
				public uint ClearScore2 { get; set; }

				[global::ProtoBuf.ProtoMember(6, Name = "clear_time_3", IsRequired = true)]
				public uint ClearTime3 { get; set; }

				[global::ProtoBuf.ProtoMember(7, Name = "clear_score_3", IsRequired = true)]
				public uint ClearScore3 { get; set; }

				[global::ProtoBuf.ProtoMember(8, Name = "total_clear_time", IsRequired = true)]
				public uint TotalClearTime { get; set; }

				[global::ProtoBuf.ProtoMember(9, Name = "total_clear_score", IsRequired = true)]
				public uint TotalClearScore { get; set; }

            }
            
        }

        [global::ProtoBuf.ProtoContract()]
        public partial class MobileUserGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"customize", IsRequired = true)]
            public CustomizeGroup Customize { get; set; }

            // [global::ProtoBuf.ProtoMember(4, Name = @"playing_messages")]
            // public global::System.Collections.Generic.List<CommandMessageGroup> PlayingMessages { get; } = new();
            // [global::ProtoBuf.ProtoMember(5, Name = @"result_messages")]
            // public global::System.Collections.Generic.List<CommandMessageGroup> ResultMessages { get; } = new();
            //
            // [global::ProtoBuf.ProtoMember(31, Name = @"online_shuffle_playing_messages")]
            // public global::System.Collections.Generic.List<CommandMessageGroup> OnlineShufflePlayingMessages { get; } = new();
            //
            // [global::ProtoBuf.ProtoMember(32, Name = @"online_shuffle_result_messages")]
            // public global::System.Collections.Generic.List<CommandMessageGroup> OnlineShuffleResultMessages { get; } = new();
            //
            // [global::ProtoBuf.ProtoMember(16, Name = @"opening_messages")]
            // public global::System.Collections.Generic.List<CommandMessageGroup> OpeningMessages { get; } = new();
            //
            // [global::ProtoBuf.ProtoMember(33, Name = @"online_shuffle_opening_messages")]
            // public global::System.Collections.Generic.List<CommandMessageGroup> OnlineShuffleOpeningMessages { get; } = new();

            [global::ProtoBuf.ProtoMember(8, Name = @"mst_mobile_suit_id", IsRequired = true)]
            public uint MstMobileSuitId { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"armor_level", IsRequired = true)]
            public uint ArmorLevel { get; set; }
            [global::ProtoBuf.ProtoMember(10, Name = @"shoot_attack_level", IsRequired = true)]
            public uint ShootAttackLevel { get; set; }
            [global::ProtoBuf.ProtoMember(11, Name = @"infight_attack_level", IsRequired = true)]
            public uint InfightAttackLevel { get; set; }
            [global::ProtoBuf.ProtoMember(12, Name = @"booster_level", IsRequired = true)]
            public uint BoosterLevel { get; set; }
            [global::ProtoBuf.ProtoMember(13, Name = @"ex_gauge_level", IsRequired = true)]
            public uint ExGaugeLevel { get; set; }
            [global::ProtoBuf.ProtoMember(14, Name = @"ai_level", IsRequired = true)]
            public uint AiLevel { get; set; }

            [global::ProtoBuf.ProtoMember(15, Name = @"gamepad")]
            public GamepadGroup Gamepad { get; set; }

            [global::ProtoBuf.ProtoMember(18, Name = @"burst_type", IsRequired = true)]
            public uint BurstType { get; set; }

            [global::ProtoBuf.ProtoMember(19, Name = @"paid_flag", IsRequired = true)]
            public bool PaidFlag { get; set; }

            [global::ProtoBuf.ProtoMember(20, Name = @"radar_type", IsRequired = true)]
            public bool RadarType { get; set; }

            //[global::ProtoBuf.ProtoMember(21)]
            //public OnlineTagInfo online_tag_info { get; set; }

            [global::ProtoBuf.ProtoMember(22, Name = @"message_position", IsRequired = true)]
            public CommandMessagePostion MessagePosition { get; set; }

            [global::ProtoBuf.ProtoMember(23, Name = @"playing_stamp_flag", IsRequired = true)]
            public bool PlayingStampFlag { get; set; }

            [global::ProtoBuf.ProtoMember(24, Name = @"mobile_user_id", IsRequired = true)]
            public uint MobileUserId { get; set; }

            [global::ProtoBuf.ProtoMember(26, Name = @"player_sticker")]
            public global::System.Collections.Generic.List<PlayerSticker> PlayerStickers { get; } = new();
            
            [global::ProtoBuf.ProtoMember(25, Name = @"partner_recruit_am_id_nglist")]
            public uint[] PartnerRecruitAmIdNglists { get; set; }
            
            [global::ProtoBuf.ProtoMember(29, Name = @"quick_start")]
            public QuickStartGroup QuickStart { get; set; }
            
            [global::ProtoBuf.ProtoMember(44, Name = @"triad_team_name", IsRequired = true)] // 44
            public string TriadTeamName { get; set; }

            [global::ProtoBuf.ProtoMember(10045, Name = @"triad_background_parts_id", IsRequired = true)] // 45
            public uint TriadBackgroundPartsId { get; set; }

            //[global::ProtoBuf.ProtoMember(10046, Name = @"class_match_title_customize", IsRequired = true)] // 46
            //public TitleCustomize ClassMatchTitleCustomize { get; set; }
            //[global::ProtoBuf.ProtoMember(10047, Name = @"triad_title_customize", IsRequired = true)] // 47
            //public TitleCustomize TriadTitleCustomize { get; set; }

            [global::ProtoBuf.ProtoMember(36, Name = @"tag_teams")]
            public global::System.Collections.Generic.List<TagTeamGroup2> TagTeams { get; } = new();

            [global::ProtoBuf.ProtoMember(27, Name = @"mute_flag", IsRequired = true)]
            public bool MuteFlag { get; set; }

            [global::ProtoBuf.ProtoMember(43, Name = @"support_ticket_remains")]
            public uint SupportTicketRemains { get; set; }
            
            [global::ProtoBuf.ProtoMember(30, Name = @"pcoin_ticket_num", IsRequired = true)]
            public uint p30 { get; set; } = 0;
            
            [global::ProtoBuf.ProtoMember(31, Name = @"solo_command_messages")]
            public CommandMessageGroup p31 { get; } = new();
            [global::ProtoBuf.ProtoMember(32, Name = @"team_command_messages")]
            public CommandMessageGroup p32 { get; } = new();
            [global::ProtoBuf.ProtoMember(33, Name = @"instant_team_command_messages")]
            public CommandMessageGroup p33 { get; } = new();
            
            [global::ProtoBuf.ProtoMember(34, Name = @"command_message_auto_flag", IsRequired = true)]
            public uint p34 { get; set; } = 1;
            
            [global::ProtoBuf.ProtoMember(35, Name = "vs_route_battle_data")] // save_data_info
            public VsRouteBattleDataGroup VsRouteBattleData { get; set; }
            
            [global::ProtoBuf.ProtoMember(37, Name = @"group_id", IsRequired = true)]
            public uint group_id { get; set; } = 1;
            [global::ProtoBuf.ProtoMember(38, Name = "group_name")]
            public string p38 { get; set; } = "RE0-486";
            [global::ProtoBuf.ProtoMember(39, Name = "group_plate_id")]
            public uint p39 { get; set; }
            [global::ProtoBuf.ProtoMember(40, Name = "group_emblem_base_id")]
            public uint p40 { get; set; }
            [global::ProtoBuf.ProtoMember(41, Name = "group_emblem_parts_id")]
            public uint p41 { get; set; }
            [global::ProtoBuf.ProtoMember(42, Name = "group_emblem_effect_id")]
            public uint p42 { get; set; }
            
            [global::ProtoBuf.ProtoMember(48)]
            public uint p48 { get; set; } = 486;

            [global::ProtoBuf.ProtoContract()]
            public partial class CustomizeGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"default_gauge_design_id", IsRequired = true)]
                public uint DefaultGaugeDesignId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"default_bgm_settings")]
                public uint[] DefaultBgmSettings { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"default_bgm_play_method", IsRequired = true)]
                public uint DefaultBgmPlayMethod { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"stage_randoms")]
                public uint[] StageRandoms { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"bgm_safe_mode", IsRequired = true)]
                public uint p5 { get; set; } = 0;
            }

            [global::ProtoBuf.ProtoContract()]
            public partial class CommandMessageGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"command", IsRequired = true)]
                public uint Command { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"message_text", IsRequired = true)]
                public string MessageText { get; set; } = "";

                [global::ProtoBuf.ProtoMember(3, Name = @"unique_message_id", IsRequired = true)]
                public uint UniqueMessageId { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"p4", IsRequired = true)]
                public string p4 { get; set; } = "";
                [global::ProtoBuf.ProtoMember(5, Name = @"p5", IsRequired = true)]
                public uint p5 { get; set; } = 0;
                [global::ProtoBuf.ProtoMember(6, Name = @"p6", IsRequired = true)]
                public string p6 { get; set; } = "";
                [global::ProtoBuf.ProtoMember(7, Name = @"p7", IsRequired = true)]
                public uint p7 { get; set; } = 0;
                [global::ProtoBuf.ProtoMember(8, Name = @"p8", IsRequired = true)]
                public string p8 { get; set; } = "";
                [global::ProtoBuf.ProtoMember(9, Name = @"p9", IsRequired = true)]
                public uint p9 { get; set; } = 0;
                [global::ProtoBuf.ProtoMember(10, Name = @"p10", IsRequired = true)]
                public string p10 { get; set; } = "";
                [global::ProtoBuf.ProtoMember(11, Name = @"p11", IsRequired = true)]
                public uint p11 { get; set; } = 0;
                [global::ProtoBuf.ProtoMember(12, Name = @"p12", IsRequired = true)]
                public string p12 { get; set; } = "";

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class GamepadGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"x_key", IsRequired = true)]
                public uint XKey { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"y_key", IsRequired = true)]
                public uint YKey { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"a_key", IsRequired = true)]
                public uint AKey { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"b_key", IsRequired = true)]
                public uint BKey { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"lb_key", IsRequired = true)]
                public uint LbKey { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"rb_key", IsRequired = true)]
                public uint RbKey { get; set; }

                [global::ProtoBuf.ProtoMember(7, Name = @"lt_key", IsRequired = true)]
                public uint LtKey { get; set; }

                [global::ProtoBuf.ProtoMember(8, Name = @"rt_key", IsRequired = true)]
                public uint RtKey { get; set; }

                [global::ProtoBuf.ProtoMember(9, Name = @"lsb_key", IsRequired = true)]
                public uint LsbKey { get; set; }

                [global::ProtoBuf.ProtoMember(10, Name = @"rsb_key", IsRequired = true)]
                public uint RsbKey { get; set; }

            }

            #region // OnlineTagInfo
            // [global::ProtoBuf.ProtoContract()]
            // public partial class OnlineTagInfo : global::ProtoBuf.IExtensible
            // {
            //     private global::ProtoBuf.IExtension __pbn__extensionData;
            //     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            //         => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            //
            //     [global::ProtoBuf.ProtoMember(1, Name = @"tag_team_partners")]
            //     public global::System.Collections.Generic.List<OnlineTagPartner> TagTeamPartners { get; } = new();
            //
            //     [global::ProtoBuf.ProtoMember(2)]
            //     public QuickTagPartner quick_tag_partner { get; set; }
            //
            //     [global::ProtoBuf.ProtoContract()]
            //     public partial class OnlineTagPartner : global::ProtoBuf.IExtensible
            //     {
            //         private global::ProtoBuf.IExtension __pbn__extensionData;
            //         global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            //             => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            //
            //         [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
            //         public uint Id { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
            //         public string Name { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(3, Name = @"player_level_id", IsRequired = true)]
            //         public uint PlayerLevelId { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(4, Name = @"prestige_id", IsRequired = true)]
            //         public uint PrestigeId { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(5, Name = @"class_id_team", IsRequired = true)]
            //         public uint ClassIdTeam { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(6, Name = @"top_point_rank_team", IsRequired = true)]
            //         public uint TopPointRankTeam { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(7, Name = @"top_point_rank_num_team", IsRequired = true)]
            //         public uint TopPointRankNumTeam { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(8, Name = @"rate_team")]
            //         public float RateTeam
            //         {
            //             get => __pbn__RateTeam.GetValueOrDefault();
            //             set => __pbn__RateTeam = value;
            //         }
            //         public bool ShouldSerializeRateTeam() => __pbn__RateTeam != null;
            //         public void ResetRateTeam() => __pbn__RateTeam = null;
            //         private float? __pbn__RateTeam;
            //
            //     }
            //
            //     [global::ProtoBuf.ProtoContract()]
            //     public partial class QuickTagPartner : global::ProtoBuf.IExtensible
            //     {
            //         private global::ProtoBuf.IExtension __pbn__extensionData;
            //         global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            //             => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            //
            //         [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
            //         public uint Id { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
            //         public string Name { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(3, Name = @"player_level_id", IsRequired = true)]
            //         public uint PlayerLevelId { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(4, Name = @"prestige_id", IsRequired = true)]
            //         public uint PrestigeId { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(5, Name = @"class_id_team", IsRequired = true)]
            //         public uint ClassIdTeam { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(6, Name = @"top_point_rank_team", IsRequired = true)]
            //         public uint TopPointRankTeam { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(7, Name = @"top_point_rank_num_team", IsRequired = true)]
            //         public uint TopPointRankNumTeam { get; set; }
            //
            //         [global::ProtoBuf.ProtoMember(8, Name = @"rate_team")]
            //         public float RateTeam
            //         {
            //             get => __pbn__RateTeam.GetValueOrDefault();
            //             set => __pbn__RateTeam = value;
            //         }
            //         public bool ShouldSerializeRateTeam() => __pbn__RateTeam != null;
            //         public void ResetRateTeam() => __pbn__RateTeam = null;
            //         private float? __pbn__RateTeam;
            //
            //     }
            //
            // }
            #endregion // OnlineTagInfo

            [global::ProtoBuf.ProtoContract()]
            public partial class PlayerSticker : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"mst_mobile_suit_id", IsRequired = true)]
                public uint MstMobileSuitId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"pose_id", IsRequired = true)] // 4
                public uint PoseId { get; set; } // uint[]

                [global::ProtoBuf.ProtoMember(9, Name = @"sub_background_id", IsRequired = true)] // 5
                public uint BasePanelId { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"comment_parts_a_id", IsRequired = true)]
                public uint CommentPartsAId { get; set; }

                [global::ProtoBuf.ProtoMember(10, Name = @"comment_parts_b_id", IsRequired = true)]
                public uint CommentPartsBId { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"tracker")]
                public global::System.Collections.Generic.List<Tracker> Trackers { get; } = new();

                [global::ProtoBuf.ProtoMember(4, Name = @"sticker_background_id", IsRequired = true)] // 11
                public uint StickerBackgroundId { get; set; }
                [global::ProtoBuf.ProtoMember(5, Name = @"sticker_effect_id", IsRequired = true)] // 12
                public uint StickerEffectId { get; set; }

                [global::ProtoBuf.ProtoMember(13, Name = @"p13", IsRequired = true)]
                public uint p13 { get; set; } = 0;
                
                // 6 pilot_image_disp_flag
                // 7 costume_id []
                // 8 cutin_image_use_flag
                // 9 sub_background_id
                
                [global::ProtoBuf.ProtoContract()]
                public partial class Tracker : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
                    public uint Type { get; set; }

                    [global::ProtoBuf.ProtoMember(2, Name = @"rarity")]
                    public uint Rarity
                    {
                       get => __pbn__Rarity.GetValueOrDefault();
                       set => __pbn__Rarity = value;
                    }
                    public bool ShouldSerializeRarity() => __pbn__Rarity != null;
                    public void ResetRarity() => __pbn__Rarity = null;
                    private uint? __pbn__Rarity;

                    [global::ProtoBuf.ProtoMember(3, Name = @"text_id", IsRequired = true)]
                    public uint TextId { get; set; }

                    [global::ProtoBuf.ProtoMember(4, Name = @"intger_tracker_value")]
                    public uint IntgerTrackerValue
                    {
                       get => __pbn__IntgerTrackerValue.GetValueOrDefault();
                       set => __pbn__IntgerTrackerValue = value;
                    }
                    public bool ShouldSerializeIntgerTrackerValue() => __pbn__IntgerTrackerValue != null;
                    public void ResetIntgerTrackerValue() => __pbn__IntgerTrackerValue = null;
                    private uint? __pbn__IntgerTrackerValue;

                    [global::ProtoBuf.ProtoMember(5, Name = @"float_tracker_value")]
                    public float FloatTrackerValue
                    {
                       get => __pbn__FloatTrackerValue.GetValueOrDefault();
                       set => __pbn__FloatTrackerValue = value;
                    }
                    public bool ShouldSerializeFloatTrackerValue() => __pbn__FloatTrackerValue != null;
                    public void ResetFloatTrackerValue() => __pbn__FloatTrackerValue = null;
                    private float? __pbn__FloatTrackerValue;
                    
                    [global::ProtoBuf.ProtoMember(6, Name = "custom_text")]
                    public string CustomText { get; set; }

                }

            }
            
            [global::ProtoBuf.ProtoContract()]
            public partial class QuickStartGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
                
                [global::ProtoBuf.ProtoMember(1, Name = "game_mode", IsRequired = true)]
                public uint GameMode { get; set; }
                
                [global::ProtoBuf.ProtoMember(2, Name = "rule_type", IsRequired = true)]
                public uint RuleType { get; set; }
                [global::ProtoBuf.ProtoMember(3, Name = "team_type", IsRequired = true)]
                public uint TeamType { get; set; }
                
                [global::ProtoBuf.ProtoMember(4, Name = "mobile_suit_id", IsRequired = true)]
                public uint MstMobileSuitId { get; set; }
                [global::ProtoBuf.ProtoMember(5, Name = "burst_type", IsRequired = true)]
                public uint BurstType { get; set; }
                
                [global::ProtoBuf.ProtoMember(6, Name = "mobile_suit_id2", IsRequired = true)]
                public uint PartnerMobileSuitId { get; set; }
                [global::ProtoBuf.ProtoMember(7, Name = "burst_type2", IsRequired = true)]
                public uint PartnerBurstType { get; set; }
                
                [global::ProtoBuf.ProtoMember(8, Name = "battle_stage_id", IsRequired = true)]
                public uint BattleStageId { get; set; }
                
            }
            
            [global::ProtoBuf.ProtoContract()]
            public partial class VsRouteBattleDataGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = "pattern_id", IsRequired = true)]
                public uint PatternId { get; set; } = 0;
                
                [global::ProtoBuf.ProtoMember(2, Name = "difficulty", IsRequired = true)]
                public uint Difficulty { get; set; }
                
                [global::ProtoBuf.ProtoMember(3, Name = "stage_id", IsRequired = true)]
                public uint StageId { get; set; } // 0<x<3
                
                [global::ProtoBuf.ProtoMember(4, Name = "boss1", IsRequired = true)]
                public uint Boss1 { get; set; }
                [global::ProtoBuf.ProtoMember(5, Name = "boss2", IsRequired = true)]
                public uint Boss2 { get; set; }
                
                [global::ProtoBuf.ProtoMember(6, Name = "team_cost_max", IsRequired = true)]
                public uint TeamCostMax { get; set; }
                
                [global::ProtoBuf.ProtoMember(7, Name = "team_cost_curr", IsRequired = true)]
                public uint TeamCostCurr { get; set; }
                
                [global::ProtoBuf.ProtoMember(8, Name = "mobile_suit_id", IsRequired = true)]
                public uint MobileSuitId { get; set; }

                [global::ProtoBuf.ProtoMember(9, Name = "chips", IsRequired = true)]
                public uint[] Chips { get; set; } = [];
                
                [global::ProtoBuf.ProtoMember(10, Name = "url", IsRequired = true)]
                public string Url { get; set; } = "";

            }
            
        }
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class TagTeamGroup2 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
    public uint Id { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
    public string Name { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"partner_id", IsRequired = true)]
    public uint PartnerId { get; set; }

    [global::ProtoBuf.ProtoMember(13, Name = @"background_parts_id", IsRequired = true)]
    public uint BackgroundPartsId { get; set; }

    [global::ProtoBuf.ProtoMember(14, Name = @"effect_id", IsRequired = true)]
    public uint EffectId { get; set; }

    [global::ProtoBuf.ProtoMember(15, Name = @"emblem_id", IsRequired = true)]
    public uint EmblemId { get; set; }

    [global::ProtoBuf.ProtoMember(16, Name = @"skill_point", IsRequired = true)]
    public uint SkillPoint { get; set; }

    [global::ProtoBuf.ProtoMember(17, Name = @"skill_point_boost", IsRequired = true)]
    public uint SkillPointBoost { get; set; }

    [global::ProtoBuf.ProtoMember(18, Name = @"bgm_id", IsRequired = true)]
    public uint BgmId { get; set; }

    //[global::ProtoBuf.ProtoMember(11, Name = @"name_color_id", IsRequired = true)]
    //public uint NameColorId { get; set; }
    //[global::ProtoBuf.ProtoMember(12, Name = @"boost_remains", IsRequired = true)]
    //public uint BoostRemains { get; set; }

    [global::ProtoBuf.ProtoMember(19, Name = @"partner_name", IsRequired = true)]
    public string PartnerName { get; set; } = "";

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
//#endregion
