// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Response2
{
	// 1006
    [global::ProtoBuf.ProtoContract()]
    public partial class LoadClassMatch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"constant_rate", IsRequired = true)] // 1
        public uint ConstantRate { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"win_score_coefficient", IsRequired = true)] // 2
        public uint WinScoreCoefficient { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"class_change_initial_rate")]
        public global::System.Collections.Generic.List<ClassChangeInitialRate> ClassChangeInitialRates { get; } = new();
        
		[global::ProtoBuf.ProtoMember(4, Name = @"grade_thresholds", IsRequired = true)]
        public global::System.Collections.Generic.List<ClassGradeThreshold> GradeThresholds { get; } = new();
        
        [global::ProtoBuf.ProtoMember(5, Name = @"search_ratios", IsRequired = true)]
        public SearchRatioTable SearchRatios { get; set; }
        
        [global::ProtoBuf.ProtoMember(6, Name = @"class_matching_time_schedule")] // 15
        public global::System.Collections.Generic.List<ClassMatchingTimeSchedule> ClassMatchingTimeSchedules { get; } = new();
        [global::ProtoBuf.ProtoMember(7, Name = @"class_matching_pattern_table")] // 16
        public global::System.Collections.Generic.List<ClassMatchingPatternTable> ClassMatchingPatternTables { get; } = new();
        [global::ProtoBuf.ProtoMember(8, Name = @"class_matching_request_table")] // 17
        public global::System.Collections.Generic.List<ClassMatchingRequest> ClassMatchingRequestTables { get; } = new();
        
        [global::ProtoBuf.ProtoMember(9, Name = @"initial_rate", IsRequired = true)]
        public uint InitialRate { get; set; } // Rate
        
        [global::ProtoBuf.ProtoMember(10, Name = @"consecutive_win_grade")]
        public global::System.Collections.Generic.List<ConsecutiveGrade> ConsecutiveWinGrades { get; } = new();
        [global::ProtoBuf.ProtoMember(11, Name = @"consecutive_lose_grade")]
        public global::System.Collections.Generic.List<ConsecutiveGrade> ConsecutiveLoseGrades { get; } = new();
        
        [global::ProtoBuf.ProtoContract()]
        public partial class ClassChangeInitialRate : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
                
            [global::ProtoBuf.ProtoMember(1, Name = @"team_type", IsRequired = true)]
            public uint TeamType { get; set; }
            
            [global::ProtoBuf.ProtoMember(2, Name = @"class_id", IsRequired = true)]
            public uint ClassId { get; set; }
            
            [global::ProtoBuf.ProtoMember(3, Name = @"up_default_rate", IsRequired = true)]
            public uint UpDefaultRate { get; set; }
            
            [global::ProtoBuf.ProtoMember(4, Name = @"down_default_rate", IsRequired = true)]
            public uint DownDefaultRate { get; set; }
        }
        
        [global::ProtoBuf.ProtoContract()]
        public partial class ClassGradeThreshold : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
                
            [global::ProtoBuf.ProtoMember(1, Name = @"team_type", IsRequired = true)]
            public uint TeamType { get; set; }
            
            [global::ProtoBuf.ProtoMember(2, Name = @"class_id", IsRequired = true)]
            public uint ClassId { get; set; }
            [global::ProtoBuf.ProtoMember(3, Name = @"grade_id", IsRequired = true)]
            public uint GradeId { get; set; }
            
            [global::ProtoBuf.ProtoMember(4, Name = @"max_rate", IsRequired = true)]
            public uint MaxRate { get; set; }
            [global::ProtoBuf.ProtoMember(5, Name = @"min_rate", IsRequired = true)]
            public uint MinRate { get; set; }
        }
        
        [global::ProtoBuf.ProtoContract()]
        public partial class SearchRatioTable : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            
            [global::ProtoBuf.ProtoMember(1, Name = @"search_ratio_solo")]
            public global::System.Collections.Generic.List<SearchRatio> SearchRatioSolo { get; } = new();
            [global::ProtoBuf.ProtoMember(2, Name = @"search_ratio_team")]
            public global::System.Collections.Generic.List<SearchRatio> SearchRatioTeam { get; } = new();
            
            [global::ProtoBuf.ProtoContract()]
            public partial class SearchRatio : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
                    
                [global::ProtoBuf.ProtoMember(1, Name = @"class_id", IsRequired = true)]
                public uint ClassId { get; set; }
                [global::ProtoBuf.ProtoMember(2, Name = @"level_id", IsRequired = true)]
                public uint LevelId { get; set; }
                [global::ProtoBuf.ProtoMember(3, Name = @"num", IsRequired = true)]
                public uint Num { get; set; }
                [global::ProtoBuf.ProtoMember(4, Name = @"search_ratio", IsRequired = true)]
                public uint Ratio { get; set; }
            }
        }
        
        [global::ProtoBuf.ProtoContract()]
        public partial class ConsecutiveGrade : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
                
            [global::ProtoBuf.ProtoMember(1, Name = @"consecutive_num_start", IsRequired = true)]
            public uint ConsecutiveNumStart { get; set; }
            [global::ProtoBuf.ProtoMember(2, Name = @"consecutive_num_end", IsRequired = true)]
            public uint ConsecutiveNumEnd { get; set; }
            [global::ProtoBuf.ProtoMember(3, Name = @"grade_num", IsRequired = true)]
            public uint GradeNum { get; set; }
        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ClassMatchingTimeSchedule : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"start_at", IsRequired = true)]
            public ulong StartAt { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"end_at", IsRequired = true)]
            public ulong EndAt { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"pattern_id", IsRequired = true)]
            public uint PatternId { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ClassMatchingPatternTable : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"pattern_id", IsRequired = true)]
            public uint PatternId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"class_matching_solo")]
            public global::System.Collections.Generic.List<ClassMatchingPattern> ClassMatchingSoloes { get; } = new();
            [global::ProtoBuf.ProtoMember(3, Name = @"class_matching_team")]
            public global::System.Collections.Generic.List<ClassMatchingPattern> ClassMatchingTeams { get; } = new();

            [global::ProtoBuf.ProtoContract()]
            public partial class ClassMatchingPattern : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"class_id", IsRequired = true)]
                public uint ClassId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"level_id", IsRequired = true)]
                public uint LevelId { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"grade_id_start", IsRequired = true)]
                public uint GradeIdStart { get; set; }
                [global::ProtoBuf.ProtoMember(4, Name = @"grade_id_end", IsRequired = true)]
                public uint GradeIdEnd { get; set; }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ClassMatchingRequest : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"room_search_id", IsRequired = true)]
            public uint RoomSearchId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"matching_try_num", IsRequired = true)]
            public uint MatchingTryNum { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"seq_num", IsRequired = true)]
            public uint SeqNum { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"make_room_flag", IsRequired = true)]
            public bool MakeRoomFlag { get; set; }

        }

    }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
