// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Response2
{
    // 1005
    [global::ProtoBuf.ProtoContract()]
    public partial class LoadRankMatch2 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rank_match_season")]
        public global::System.Collections.Generic.List<RankMatchSeasonInfo> RankMatchSeasons { get; } = new();

        [global::ProtoBuf.ProtoMember(2, Name = @"rank_match_active")]
        public global::System.Collections.Generic.List<RankMatchActive> RankMatchActives { get; } = new();

        [global::ProtoBuf.ProtoMember(3, Name = @"rank_match_point_threshold")]
        public global::System.Collections.Generic.List<RankMatchPointThreshold> RankMatchPointThresholds { get; } = new();
        [global::ProtoBuf.ProtoMember(4, Name = @"rank_match_win_point_solo")]
        public global::System.Collections.Generic.List<RankMatchWinPoint> RankMatchWinPointSoloes { get; } = new();
        [global::ProtoBuf.ProtoMember(5, Name = @"rank_match_lose_point_solo")]
        public global::System.Collections.Generic.List<RankMatchLosePoint> RankMatchLosePointSoloes { get; } = new();

        [global::ProtoBuf.ProtoMember(6, Name = @"rank_base_win_point", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public int RankBaseWinPoint { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"rank_base_lose_point", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public int RankBaseLosePoint { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"rank_lose_result_bonus", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public int RankLoseResultBonus { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"rank_win_bonus")]
        public global::System.Collections.Generic.List<RankMatchWinBonus> RankWinBonus { get; } = new();

        [global::ProtoBuf.ProtoMember(10, Name = @"rank_match_num_days", IsRequired = true)]
        public uint RankMatchNumDays { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"rank_match_win_point_team")]
        public global::System.Collections.Generic.List<RankMatchWinPoint> RankMatchWinPointTeams { get; } = new();

        [global::ProtoBuf.ProtoMember(12, Name = @"rank_match_lose_point_team")]
        public global::System.Collections.Generic.List<RankMatchLosePoint> RankMatchLosePointTeams { get; } = new();

        [global::ProtoBuf.ProtoMember(13, Name = @"rank_matching_time_schedule")]
        public global::System.Collections.Generic.List<RankMatchingTimeSchedule> RankMatchingTimeSchedules { get; } = new();

        [global::ProtoBuf.ProtoMember(14, Name = @"rank_matching_pattern_table")]
        public global::System.Collections.Generic.List<RankMatchingPatternTable> RankMatchingPatternTables { get; } = new();

        [global::ProtoBuf.ProtoMember(15, Name = @"rank_matching_condition_table")]
        public global::System.Collections.Generic.List<RankMatchingConditionTable> RankMatchingConditionTables { get; } = new();

        [global::ProtoBuf.ProtoMember(16, Name = @"rank_win_point_bonus_2", IsRequired = true)]
        public uint RankWinPointBonus2 { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"rank_win_point_bonus_1", IsRequired = true)]
        public uint RankWinPointBonus1 { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"rank_lose_point_bonus_2", IsRequired = true)]
        public uint RankLosePointBonus2 { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"rank_lose_point_bonus_1", IsRequired = true)]
        public uint RankLosePointBonus1 { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"rank_win_point_bonus_3", IsRequired = true)]
        public uint RankWinPointBonus3 { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"rank_lose_point_bonus_3", IsRequired = true)]
        public uint RankLosePointBonus3 { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"exx_threshold_order", IsRequired = true)]
        public uint ExxThresholdOrder { get; set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"exx_threshold_point", IsRequired = true)]
        public uint ExxThresholdPoint { get; set; }


        [global::ProtoBuf.ProtoContract()]
        public partial class RankMatchSeasonInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"season_id", IsRequired = true)]
            public uint SeasonId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"start_date", IsRequired = true)]
            public ulong StartDate { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"end_date", IsRequired = true)]
            public ulong EndDate { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"off_end_date", IsRequired = true)]
            public ulong OffEndDate { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class RankMatchActive : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"team_type", IsRequired = true)]
            public uint TeamType { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"rank_zone", IsRequired = true)]
            public uint RankZone { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"matching_rank_zone", IsRequired = true)]
            public uint MatchingRankZone { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class RankMatchPointThreshold : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"matching_rank_id", IsRequired = true)]
            public uint MatchingRankId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"upper_point", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
            public int UpperPoint { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"lower_point", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
            public int LowerPoint { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"init_num", IsRequired = true)]
            public uint InitNum { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class RankMatchWinPoint : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"level", IsRequired = true)]
            public uint Level { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"point", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
            public int Point { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class RankMatchLosePoint : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"rank_zone_id", IsRequired = true)]
            public uint RankZoneId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"point", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
            public int Point { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class RankMatchWinBonus : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"rank_zone_id", IsRequired = true)]
            public uint RankZoneId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"point", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
            public int Point { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class RankMatchingTimeSchedule : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"start_at", IsRequired = true)]
            public ulong StartAt { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"end_at", IsRequired = true)]
            public ulong EndAt { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"pattern_id", IsRequired = true)]
            public uint PatternId { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"condition_id", IsRequired = true)]
            public uint ConditionId { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class RankMatchingPatternTable : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"pattern_id", IsRequired = true)]
            public uint PatternId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"rank_matching_solo")]
            public global::System.Collections.Generic.List<RankMatchingPattern> RankMatchingSoloes { get; } = new();

            [global::ProtoBuf.ProtoMember(3, Name = @"rank_matching_team")]
            public global::System.Collections.Generic.List<RankMatchingPattern> RankMatchingTeams { get; } = new();

            [global::ProtoBuf.ProtoContract()]
            public partial class RankMatchingPattern : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"matching_div", IsRequired = true)]
                public uint MatchingDiv { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"rank_id", IsRequired = true)]
                public uint RankId { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"level", IsRequired = true)]
                public uint Level { get; set; }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class RankMatchingConditionTable : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"condition_id", IsRequired = true)]
            public uint ConditionId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"rank_matching_condition_solo")]
            public global::System.Collections.Generic.List<RankMatchingCondition> RankMatchingConditionSoloes { get; } = new();

            [global::ProtoBuf.ProtoMember(3, Name = @"rank_matching_condition_team")]
            public global::System.Collections.Generic.List<RankMatchingCondition> RankMatchingConditionTeams { get; } = new();

            [global::ProtoBuf.ProtoContract()]
            public partial class RankMatchingCondition : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"matching_div", IsRequired = true)]
                public uint MatchingDiv { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"matching_try_num", IsRequired = true)]
                public uint MatchingTryNum { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"seq_num", IsRequired = true)]
                public uint SeqNum { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"make_room_flag", IsRequired = true)]
                public bool MakeRoomFlag { get; set; }

            }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
