// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Response2
{
	// 1004
    [global::ProtoBuf.ProtoContract()]
    public partial class LoadGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"release_ms_id")]
        public uint[] ReleaseMsIds { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"new_ms_id")]
        public uint[] NewMsIds { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"displayable_ms_id")]
        public uint[] DisplayableMsIds { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"release_guest_nav_id")]
        public uint[] ReleaseGuestNavIds { get; set; }

        [global::ProtoBuf.ProtoMember(58, Name = @"release_game_rule")] // 7
        public uint[] ReleaseGameRules { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)] // 18
        public OnVsInfo on_vs_info { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"update_ms_id")] // 19
        public uint[] UpdateMsIds { get; set; }

        [global::ProtoBuf.ProtoMember(10022)] // 22
        public MedalInfo medal_info { get; set; }

        //[global::ProtoBuf.ProtoMember(60, Name = @"release_cpu_course", IsRequired = true)] // 23
        //public global::System.Collections.Generic.List<ReleaseCpuCourse> ReleaseCpuCourses { get; } = new();

        [global::ProtoBuf.ProtoMember(61, Name = @"release_cpu_scene")] // 24
        public uint[] ReleaseCpuScenes { get; set; }

        [global::ProtoBuf.ProtoMember(62, Name = @"mst_mobile_suit_id")] // 25
        public uint[] MstMobileSuitIds { get; set; }

        [global::ProtoBuf.ProtoMember(7)] // 27
        public WeeklyRankInfo _weekly_rank_info { get; set; } = new();

        [global::ProtoBuf.ProtoMember(8, Name = @"training_time_limit", IsRequired = true)] // 30
        public uint TrainingTimeLimit { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"newcard_campaign_flag", IsRequired = true)] // 33
        public bool _NewcardCampaignFlag { get; set; } = true;

        [global::ProtoBuf.ProtoMember(10, Name = @"free_matching_tables")] // 34
        public global::System.Collections.Generic.List<FreeMatchingTable> FreeMatchingTables { get; } = new();
        [global::ProtoBuf.ProtoMember(11, Name = @"free_match_rank_tables")] // 35
        public global::System.Collections.Generic.List<FreeMatchingRankTable> FreeMatchRankTables { get; } = new();

        [global::ProtoBuf.ProtoMember(12, Name = @"score_display_interval")] // 36
        public uint[] ScoreDisplayIntervals { get; set; }


        [global::ProtoBuf.ProtoMember(10037, Name = @"base_win_point", IsRequired = true)] // 37
        public uint BaseWinPoint { get; set; }
        [global::ProtoBuf.ProtoMember(10038, Name = @"base_lose_point", IsRequired = true)]
        public uint BaseLosePoint { get; set; }
        [global::ProtoBuf.ProtoMember(10039, Name = @"win_bonus", IsRequired = true)]
        public uint WinBonus { get; set; }
        [global::ProtoBuf.ProtoMember(10040, Name = @"win_result_top_bonus", IsRequired = true)]
        public uint WinResultTopBonus { get; set; }
        [global::ProtoBuf.ProtoMember(10041, Name = @"lose_result_top_bonus", IsRequired = true)]
        public uint LoseResultTopBonus { get; set; }
        
        [global::ProtoBuf.ProtoMember(10042, Name = @"player_level_exp_2", IsRequired = true)]
        public uint PlayerLevelExp2 { get; set; }
        [global::ProtoBuf.ProtoMember(10043, Name = @"player_level_exp_3", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public int PlayerLevelExp3 { get; set; }
        
        [global::ProtoBuf.ProtoMember(44, Name = @"wanted_attack_level", IsRequired = true)]
        public uint WantedAttackLevel { get; set; }
        [global::ProtoBuf.ProtoMember(45, Name = @"wanted_ps_attack_level", IsRequired = true)]
        public uint WantedPsAttackLevel { get; set; }
        [global::ProtoBuf.ProtoMember(46, Name = @"wanted_ps_defence_level", IsRequired = true)]
        public uint WantedPsDefenceLevel { get; set; }
        [global::ProtoBuf.ProtoMember(47, Name = @"wanted_down_level", IsRequired = true)] // 47
        public uint WantedDownLevel { get; set; }


        [global::ProtoBuf.ProtoMember(13, Name = @"fes_setting")] // 48
        public XrossFesSetting FesSetting { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"load_game_data_ver", IsRequired = true)] // 49
        public uint LoadGameDataVer { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = "score_battle_point", IsRequired = true)] // 50
        public ScoreBattlePoint score_battle_point { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = "attack_score_setting", IsRequired = true)] // 51
        public AttackScoreSetting attack_score_setting { get; set; }
        
        //[global::ProtoBuf.ProtoMember(10052, Name = @"gp_boost_setting")] // 52
        //public GpBoostEvent GpBoostSetting { get; set; }
        //[global::ProtoBuf.ProtoMember(10054, Name = @"ob_pass_bonus_gp")] // 54
        //public uint ObPassBonusGp { get; set; }
        
        [global::ProtoBuf.ProtoMember(18, Name = "player_point_bonus_setting")] // 53
        public PlayerPointBonusEvent _PlayerPointBonusSetting { get; set; }

        [global::ProtoBuf.ProtoMember(10055, Name = @"player_level_exp_4", IsRequired = true)] // 55
        public uint player_level_exp_4 { get; set; } = 350;

        //[global::ProtoBuf.ProtoMember(10056, Name = @"p_level_bonus_rate", IsRequired = true)] // 56
        //public float PLevelBonusRate { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"mobile_suit_blocklist", IsRequired = true)] // 57
        public uint[] MobileSuitBlocklists { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"vs_player_level_point", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public int p21 { get; set; } = 50; // 100
        [global::ProtoBuf.ProtoMember(22, Name = @"cpu_player_level_point", DataFormat = global::ProtoBuf.DataFormat.ZigZag, IsRequired = true)]
        public int p22 { get; set; } = 25; // 50
        [global::ProtoBuf.ProtoMember(23, Name = @"class_win_badge_point", IsRequired = true)]
        public uint p23 { get; set; } = 0;
        [global::ProtoBuf.ProtoMember(24, Name = @"class_lose_badge_point", IsRequired = true)]
        public uint p24 { get; set; } = 0;
        [global::ProtoBuf.ProtoMember(25, Name = @"class_win_badge_bonus1", IsRequired = true)]
        public uint p25 { get; set; } = 0;
        [global::ProtoBuf.ProtoMember(26, Name = @"class_win_badge_bonus2", IsRequired = true)]
        public uint p26 { get; set; } = 0;
        [global::ProtoBuf.ProtoMember(27, Name = @"class_lose_badge_bonus", IsRequired = true)]
        public uint p27 { get; set; } = 0;
        [global::ProtoBuf.ProtoMember(28, Name = @"root_win_badge_point1", IsRequired = true)]
        public uint p28 { get; set; } = 0;
        [global::ProtoBuf.ProtoMember(29, Name = @"root_win_badge_point2", IsRequired = true)]
        public uint p29 { get; set; } = 0;
        [global::ProtoBuf.ProtoMember(30, Name = @"root_win_badge_point3", IsRequired = true)]
        public uint p30 { get; set; } = 0;
        [global::ProtoBuf.ProtoMember(31, Name = @"root_win_badge_point4", IsRequired = true)]
        public uint p31 { get; set; } = 0;
        [global::ProtoBuf.ProtoMember(32, Name = @"root_lose_badge_point", IsRequired = true)]
        public uint p32 { get; set; } = 0;
        [global::ProtoBuf.ProtoMember(33, Name = @"root_difficulty_badge_bonus1", IsRequired = true)]
        public uint p33 { get; set; } = 0;
        [global::ProtoBuf.ProtoMember(34, Name = @"root_difficulty_badge_bonus2", IsRequired = true)]
        public uint p34 { get; set; } = 0;
        [global::ProtoBuf.ProtoMember(35, Name = @"root_difficulty_badge_bonus3", IsRequired = true)]
        public uint p35 { get; set; } = 0;
        
        [global::ProtoBuf.ProtoMember(36, Name = @"stages", IsRequired = true)] // root_pattern_id
        public uint[] Stages { get; set; }


        [global::ProtoBuf.ProtoContract()]
        public partial class OnVsInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"rule_time_limit_class")] // 1
            public uint RuleTimeLimitClass { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"rule_time_limit_free")] // 2
            public uint RuleTimeLimitFree { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"rule_damage_level_team")] // 3
            public uint RuleDamageLevelTeam { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"rule_damage_level_shuffle")] // 4
            public uint RuleDamageLevelShuffle { get; set; }
            
        }

        [global::ProtoBuf.ProtoContract()]
        public partial class MedalInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"opened_at", IsRequired = true)]
            public ulong OpenedAt { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"expired_at", IsRequired = true)]
            public ulong ExpiredAt { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"result_at", IsRequired = true)]
            public ulong ResultAt { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"normal_medal", IsRequired = true)]
            public uint NormalMedal { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"plus_coin_medal", IsRequired = true)]
            public uint PlusCoinMedal { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"revenge_medal", IsRequired = true)]
            public uint RevengeMedal { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"continue_medal", IsRequired = true)]
            public uint ContinueMedal { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"reserve_medal", IsRequired = true)]
            public uint ReserveMedal { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"location_medal", IsRequired = true)]
            public uint LocationMedal { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"reward_medal", IsRequired = true)]
            public uint RewardMedal { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ReleaseCpuCourse : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"course_id", IsRequired = true)]
            public uint CourseId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"opened_at", IsRequired = true)]
            public ulong OpenedAt { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WeeklyRankInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"weekly_rank_no", IsRequired = true)]
            public uint WeeklyRankNo { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"weekly_rank_course_id", IsRequired = true)]
            public uint WeeklyRankCourseId { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class FreeMatchingTable : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"matching_rank", IsRequired = true)]
            public uint MatchingRank { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"matching_try_num", IsRequired = true)]
            public uint MatchingTryNum { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"seq_num", IsRequired = true)]
            public uint SeqNum { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"make_room_flag", IsRequired = true)]
            public bool MakeRoomFlag { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class FreeMatchingRankTable : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"win_num", IsRequired = true)]
            public uint WinNum { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"matching_rank", IsRequired = true)]
            public uint MatchingRank { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class XrossFesSetting : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"rule_type", IsRequired = true)]
            public uint RuleType { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"start_date", IsRequired = true)]
            public ulong StartDate { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"end_date", IsRequired = true)]
            public ulong EndDate { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"burst_xross_flag", IsRequired = true)]
            public bool BurstXrossFlag { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"timer", IsRequired = true)]
            public uint Timer { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"matching_border", IsRequired = true)]
            public uint MatchingBorder { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"mobile_suit_blocklist")]
            public uint[] MobileSuitBlocklists { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ScoreBattlePoint : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"score_battle_3000_point", IsRequired = true)]
            public uint ScoreBattle3000Point { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"score_battle_2500_point", IsRequired = true)]
            public uint ScoreBattle2500Point { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"score_battle_2000_point", IsRequired = true)]
            public uint ScoreBattle2000Point { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"score_battle_1500_point", IsRequired = true)]
            public uint ScoreBattle1500Point { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class AttackScoreSetting : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"last_30_count_score_times", IsRequired = true)]
            public uint Last30CountScoreTimes { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"down_score_times", IsRequired = true)]
            public uint DownScoreTimes { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"no_attack_decrease_score", IsRequired = true)]
            public uint NoAttackDecreaseScore { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class GpBoostEvent : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"start_date", IsRequired = true)]
            public ulong StartDate { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"end_date", IsRequired = true)]
            public ulong EndDate { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"bonus_gp", IsRequired = true)]
            public uint BonusGp { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class PlayerPointBonusEvent : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"start_date", IsRequired = true)]
            public ulong StartDate { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"end_date", IsRequired = true)]
            public ulong EndDate { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"point_bonus", IsRequired = true)]
            public uint PointBonus { get; set; } // float

        }
        
        [global::ProtoBuf.ProtoContract()]
        public partial class BadgeExpTable : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"badge_id", IsRequired = true)]
            public uint BadgeId { get; set; }
            [global::ProtoBuf.ProtoMember(2, Name = @"up_default_exp", IsRequired = true)]
            public uint UpDefaultExp { get; set; }
            [global::ProtoBuf.ProtoMember(3, Name = @"down_default_exp", IsRequired = true)]
            public uint DownDefaultExp { get; set; } = 0;
        }
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
