// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

//#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Response2
{
    // 1100
    [global::ProtoBuf.ProtoContract()]
    public partial class PreLoadCard : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session_id", IsRequired = true)]
        public string SessionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"acid_response")]
        public AcidResponse AcidResponse { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"mb_id")]
        public uint MbId { get; set; }
        
        [global::ProtoBuf.ProtoMember(4)]
        public Response2.PreLoadCard.LoadPlayer load_player { get; set; }
        
        [global::ProtoBuf.ProtoMember(5, Name = @"access_code")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccessCode { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"is_new_card")]
        public bool IsNewCard
        {
            get => __pbn__IsNewCard.GetValueOrDefault();
            set => __pbn__IsNewCard = value;
        }
        public bool ShouldSerializeIsNewCard() => __pbn__IsNewCard != null;
        public void ResetIsNewCard() => __pbn__IsNewCard = null;
        private bool? __pbn__IsNewCard;

        [global::ProtoBuf.ProtoMember(7, Name = @"am_id")]
        public uint AmId
        {
            get => __pbn__AmId.GetValueOrDefault();
            set => __pbn__AmId = value;
        }
        public bool ShouldSerializeAmId() => __pbn__AmId != null;
        public void ResetAmId() => __pbn__AmId = null;
        private uint? __pbn__AmId;

        [global::ProtoBuf.ProtoMember(8, Name = @"acid_error")]
        [global::System.ComponentModel.DefaultValue(AcidError.AcidSuccess)]
        public AcidError AcidError
        {
            get => __pbn__AcidError ?? AcidError.AcidSuccess;
            set => __pbn__AcidError = value;
        }
        public bool ShouldSerializeAcidError() => __pbn__AcidError != null;
        public void ResetAcidError() => __pbn__AcidError = null;
        private AcidError? __pbn__AcidError;

        [global::ProtoBuf.ProtoMember(9, Name = @"user")]
        public Response2.PreLoadCard.MobileUserGroup User { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"matching_tag")]
        public MatchingTag MatchingTag { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class LoadPlayer : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"pilot_id", IsRequired = true)]
            public uint PilotId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"last_played_at")]
            public ulong LastPlayedAt
            {
                get => __pbn__LastPlayedAt.GetValueOrDefault();
                set => __pbn__LastPlayedAt = value;
            }
            public bool ShouldSerializeLastPlayedAt() => __pbn__LastPlayedAt != null;
            public void ResetLastPlayedAt() => __pbn__LastPlayedAt = null;
            private ulong? __pbn__LastPlayedAt;

            [global::ProtoBuf.ProtoMember(3, Name = @"total_win", IsRequired = true)]
            public uint TotalWin { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"total_lose", IsRequired = true)]
            public uint TotalLose { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"player_level_id", IsRequired = true)]
            public uint PlayerLevelId { get; set; }
            [global::ProtoBuf.ProtoMember(6, Name = @"player_exp", IsRequired = true)]
            public uint PlayerExp { get; set; }

            [global::ProtoBuf.ProtoMember(10007, Name = @"prestige_id", IsRequired = true)] // 7
            public uint PrestigeId { get; set; }
            
            [global::ProtoBuf.ProtoMember(13, Name = @"vsm_after_class_change_solo", IsRequired = true)] // 13
            public uint VsmAfterClassChangeSolo { get; set; }
            [global::ProtoBuf.ProtoMember(14, Name = @"vsm_after_class_change_team", IsRequired = true)] // 14
            public uint VsmAfterClassChangeTeam { get; set; }

            [global::ProtoBuf.ProtoMember(15, Name = @"shuffle_win", IsRequired = true)]
            public uint ShuffleWin { get; set; }
            [global::ProtoBuf.ProtoMember(16, Name = @"shuffle_lose", IsRequired = true)]
            public uint ShuffleLose { get; set; }

            [global::ProtoBuf.ProtoMember(17, Name = @"team_win", IsRequired = true)]
            public uint TeamWin { get; set; }
            [global::ProtoBuf.ProtoMember(18, Name = @"team_lose", IsRequired = true)]
            public uint TeamLose { get; set; }

            [global::ProtoBuf.ProtoMember(19, Name = @"class_solo_win", IsRequired = true)]
            public uint ClassSoloWin { get; set; }
            [global::ProtoBuf.ProtoMember(20, Name = @"class_solo_lose", IsRequired = true)]
            public uint ClassSoloLose { get; set; }

            [global::ProtoBuf.ProtoMember(21, Name = @"class_team_win", IsRequired = true)]
            public uint ClassTeamWin { get; set; }
            [global::ProtoBuf.ProtoMember(22, Name = @"class_team_lose", IsRequired = true)]
            public uint ClassTeamLose { get; set; }

            [global::ProtoBuf.ProtoMember(27, Name = @"class_id_solo", IsRequired = true)]
            public uint ClassIdSolo { get; set; }
            [global::ProtoBuf.ProtoMember(28, Name = @"class_id_team", IsRequired = true)]
            public uint ClassIdTeam { get; set; }

            [global::ProtoBuf.ProtoMember(29, Name = @"fes_win")]
            public uint FesWin { get; set; }
            [global::ProtoBuf.ProtoMember(30, Name = @"fes_lose")]
            public uint FesLose { get; set; }

            [global::ProtoBuf.ProtoMember(31, Name = @"free_win")]
            public uint FreeWin { get; set; }
            [global::ProtoBuf.ProtoMember(32, Name = @"free_lose")]
            public uint FreeLose { get; set; }

            [global::ProtoBuf.ProtoMember(33, Name = @"ex_tutorial_playable_flag", IsRequired = true)]
            public bool _ExTutorialPlayableFlag { get; set; } = false;

            [global::ProtoBuf.ProtoMember(10034, Name = @"level_max_disp_flag", IsRequired = true)]
            public bool LevelMaxDispFlag { get; set; }

            [global::ProtoBuf.ProtoMember(34, Name = @"grade_solo", IsRequired = true)] // 35
            public uint GradeSolo { get; set; }
            [global::ProtoBuf.ProtoMember(35, Name = @"grade_team", IsRequired = true)] // 36
            public uint GradeTeam { get; set; }

            [global::ProtoBuf.ProtoMember(36, Name = @"top_point_rank_solo", IsRequired = true)] // 37
            public uint TopPointRankSolo { get; set; }
            [global::ProtoBuf.ProtoMember(37, Name = @"top_point_rank_num_solo", IsRequired = true)] // 38
            public uint TopPointRankNumSolo { get; set; }
            [global::ProtoBuf.ProtoMember(38, Name = @"top_point_rank_team", IsRequired = true)] // 39
            public uint TopPointRankTeam { get; set; }
            [global::ProtoBuf.ProtoMember(39, Name = @"top_point_rank_num_team", IsRequired = true)] // 42
            public uint TopPointRankNumTeam { get; set; }

            [global::ProtoBuf.ProtoMember(40, Name = @"rate_solo", IsRequired = true)]
            public float RateSolo { get; set; }
            [global::ProtoBuf.ProtoMember(41, Name = @"rate_team", IsRequired = true)]
            public float RateTeam { get; set; }

            [global::ProtoBuf.ProtoMember(10044, Name = @"p_level_boost_flag", IsRequired = true)] // 44
            public bool _PLevelBoostFlag { get; set; }
            
            [global::ProtoBuf.ProtoMember(42, Name = "grade_1_solo", IsRequired = true)]
			public uint grade_1_solo { get; set; }
			[global::ProtoBuf.ProtoMember(43, Name = "grade_1_team", IsRequired = true)]
			public uint grade_1_team { get; set; }
            
            [global::ProtoBuf.ProtoMember(148, IsRequired = true)]
            public uint p148 { get; set; } = 4;
            [global::ProtoBuf.ProtoMember(149, IsRequired = true)]
            public uint p149 { get; set; } = 8;
            [global::ProtoBuf.ProtoMember(150, IsRequired = true)]
            public uint p150 { get; set; } = 6;
            
        }

        [global::ProtoBuf.ProtoContract()]
        public partial class MobileUserGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"user_id", IsRequired = true)]
            public uint UserId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"player_name", IsRequired = true)]
            public string PlayerName { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"open_record", IsRequired = true)]
            public uint OpenRecord { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"open_echelon", IsRequired = true)]
            public uint OpenEchelon { get; set; } // 是否显示player等级

            [global::ProtoBuf.ProtoMember(5, Name = @"open_skillpoint", IsRequired = true)]
            public bool OpenSkillpoint { get; set; }

            [global::ProtoBuf.ProtoMember(6)]
            public CustomizeGroup customize_group { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"guest_navs")]
            public global::System.Collections.Generic.List<GuestNavGroup> GuestNavs { get; } = new();
            [global::ProtoBuf.ProtoMember(8, Name = @"favorite_mobile_suits")]
            public global::System.Collections.Generic.List<FavoriteMSGroup> FavoriteMobileSuits { get; } = new();
            [global::ProtoBuf.ProtoMember(9)]
            public global::System.Collections.Generic.List<SkinChangeMobilesuits> skin_change_mobilesuits { get; } = new();
            //[global::ProtoBuf.ProtoMember(10, Name = @"challenge_mis_data")]
            //public global::System.Collections.Generic.List<ChallengeMisData> ChallengeMisDatas { get; } = new();

            [global::ProtoBuf.ProtoMember(12, Name = @"game_pad_style", IsRequired = true)]
            public uint pKeyconfigNumber { get; set; } = 2; // 3

            [global::ProtoBuf.ProtoMember(11, Name = @"gp", IsRequired = true)]
            public uint Gp { get; set; }

            [global::ProtoBuf.ProtoMember(13, Name = @"player_badge_id", IsRequired = true)]
            public uint PlayerBadgeId { get; set; }
            [global::ProtoBuf.ProtoMember(14, Name = @"player_badge_exp", IsRequired = true)]
            public uint PlayerBadgeExp { get; set; }
            
            [global::ProtoBuf.ProtoMember(15, Name = @"auth_flag", IsRequired = true)]
            public bool _AuthFlag { get; set; } = true;
            
            [global::ProtoBuf.ProtoMember(16, IsRequired = true)]
            public uint p16 { get; set; } = 486;

            [global::ProtoBuf.ProtoContract()]
            public partial class CustomizeGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"default_title_customize", IsRequired = true)]
                public TitleCustomize DefaultTitleCustomize { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"mst_mobile_suit_id", IsRequired = true)]
                public uint MstMobileSuitId { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"ms_skill1", IsRequired = true)]
                public uint MsSkill1 { get; set; }
                [global::ProtoBuf.ProtoMember(4, Name = @"ms_skill2", IsRequired = true)]
                public uint MsSkill2 { get; set; }

                [global::ProtoBuf.ProtoMember(1005, Name = @"gp_boost", IsRequired = true)] // 5
                public uint GpBoost { get; set; }
                [global::ProtoBuf.ProtoMember(1006, Name = @"gp_boost_remains", IsRequired = true)] // 6
                public uint GpBoostRemains { get; set; }

                [global::ProtoBuf.ProtoMember(7, Name = @"guest_nav_boost", IsRequired = true)]
                public uint GuestNavBoost { get; set; }
                [global::ProtoBuf.ProtoMember(8, Name = @"navi_boost_remains", IsRequired = true)]
                public uint NaviBoostRemains { get; set; }

                [global::ProtoBuf.ProtoMember(1009, Name = @"tag_skill_point_boost_flag", IsRequired = true)]
                public bool TagSkillPointBoostFlag { get; set; }

                [global::ProtoBuf.ProtoMember(10, Name = @"battle_nav_advise_flag", IsRequired = true)]
                public bool BattleNavAdviseFlag { get; set; }
                [global::ProtoBuf.ProtoMember(11, Name = @"battle_nav_notify_flag", IsRequired = true)]
                public bool BattleNavNotifyFlag { get; set; }

                [global::ProtoBuf.ProtoMember(13, Name = @"quick_start_flag", IsRequired = true)]
                public uint _quick_start_flag { get; set; } = 1;

                [global::ProtoBuf.ProtoMember(12, Name = @"guest_nav_anniv_flag", IsRequired = true)]
                public bool GuestNavAnnivFlag { get; set; }

                [global::ProtoBuf.ProtoMember(14, Name = @"Command_guide_display", IsRequired = true)]
                public uint CommandGuideDisplay { get; set; }
                
                [global::ProtoBuf.ProtoMember(15, Name = "gp_boost_rate")]
                public float GpBoostRate { get; set; }
                
                [global::ProtoBuf.ProtoMember(16)]
                public float p16 { get; set; } = 1.5f;
            }

            [global::ProtoBuf.ProtoContract()]
            public partial class GuestNavGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"guest_nav_setting_flag", IsRequired = true)]
                public bool GuestNavSettingFlag { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"guest_nav_id", IsRequired = true)]
                public uint GuestNavId { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"guest_nav_costume")]
                public uint GuestNavCostume
                {
                    get => __pbn__GuestNavCostume.GetValueOrDefault();
                    set => __pbn__GuestNavCostume = value;
                }
                public bool ShouldSerializeGuestNavCostume() => __pbn__GuestNavCostume != null;
                public void ResetGuestNavCostume() => __pbn__GuestNavCostume = null;
                private uint? __pbn__GuestNavCostume;

                [global::ProtoBuf.ProtoMember(4, Name = @"guest_nav_familiarity", IsRequired = true)]
                public uint GuestNavFamiliarity { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"guest_nav_remains")]
                public uint GuestNavRemains
                {
                    get => __pbn__GuestNavRemains.GetValueOrDefault();
                    set => __pbn__GuestNavRemains = value;
                }
                public bool ShouldSerializeGuestNavRemains() => __pbn__GuestNavRemains != null;
                public void ResetGuestNavRemains() => __pbn__GuestNavRemains = null;
                private uint? __pbn__GuestNavRemains;

                [global::ProtoBuf.ProtoMember(6, Name = @"new_costume_flag", IsRequired = true)]
                public bool NewCostumeFlag { get; set; }

                [global::ProtoBuf.ProtoMember(7, Name = @"battle_nav_setting_flag", IsRequired = true)]
                public bool BattleNavSettingFlag { get; set; }

                [global::ProtoBuf.ProtoMember(8, Name = @"battle_nav_remains")]
                public uint BattleNavRemains
                {
                    get => __pbn__BattleNavRemains.GetValueOrDefault();
                    set => __pbn__BattleNavRemains = value;
                }
                public bool ShouldSerializeBattleNavRemains() => __pbn__BattleNavRemains != null;
                public void ResetBattleNavRemains() => __pbn__BattleNavRemains = null;
                private uint? __pbn__BattleNavRemains;

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class FavoriteMSGroup : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"mst_mobile_suit_id", IsRequired = true)]
                public uint MstMobileSuitId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"ms_used_num", IsRequired = true)]
                public uint MsUsedNum { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"open_skillpoint")] // 3
                public bool OpenSkillpoint { get; set; }

                [global::ProtoBuf.ProtoMember(8, Name = @"gauge_design_id", IsRequired = true)] // 4
                public uint GaugeDesignId { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"bgm_settings")] // 5
                public uint[] BgmSettings { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"bgm_play_method", IsRequired = true)] // 6
                public uint BgmPlayMethod { get; set; }

                [global::ProtoBuf.ProtoMember(7, Name = @"battle_nav_id")] // 7
                public uint BattleNavId { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"burst_type", IsRequired = true)] // 8
                public uint BurstType { get; set; }

                //[global::ProtoBuf.ProtoMember(10009, Name = @"default_title_customize", IsRequired = true)] // 9
                //public TitleCustomize DefaultTitleCustomize { get; set; }
                //[global::ProtoBuf.ProtoMember(10010, Name = @"class_match_title_customize", IsRequired = true)] // 10
                //public TitleCustomize ClassMatchTitleCustomize { get; set; }
                //[global::ProtoBuf.ProtoMember(10011, Name = @"triad_title_customize", IsRequired = true)] // 11
                //public TitleCustomize TriadTitleCustomize { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class SkinChangeMobilesuits : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"mst_mobile_suit_id", IsRequired = true)]
                public uint MstMobileSuitId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"skin_id", IsRequired = true)]
                public uint SkinId { get; set; }

            }

            #region // ChallengeMisData
            // [global::ProtoBuf.ProtoContract()]
            // public partial class ChallengeMisData : global::ProtoBuf.IExtensible
            // {
            //     private global::ProtoBuf.IExtension __pbn__extensionData;
            //     global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            //         => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            //
            //     [global::ProtoBuf.ProtoMember(1, Name = @"mission_id", IsRequired = true)]
            //     public uint MissionId { get; set; }
            //
            //     [global::ProtoBuf.ProtoMember(2, Name = @"mission_type_id", IsRequired = true)]
            //     public uint MissionTypeId { get; set; }
            //
            //     [global::ProtoBuf.ProtoMember(3, Name = @"should_complete_at", IsRequired = true)]
            //     public ulong ShouldCompleteAt { get; set; }
            //
            //     [global::ProtoBuf.ProtoMember(4, Name = @"current_num", IsRequired = true)]
            //     public uint CurrentNum { get; set; }
            //
            //     [global::ProtoBuf.ProtoMember(5, Name = @"disired_num", IsRequired = true)]
            //     public uint DisiredNum { get; set; }
            //
            //     [global::ProtoBuf.ProtoMember(6, Name = @"backcolor", IsRequired = true)]
            //     public uint Backcolor { get; set; }
            //
            //     [global::ProtoBuf.ProtoMember(7, Name = @"status", IsRequired = true)]
            //     public uint Status { get; set; }
            // }
            #endregion // ChallengeMisData
        }
    }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
//#endregion
