// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

[global::ProtoBuf.ProtoContract()]
public partial class Response2 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
    public MethodType Type { get; set; } = MethodType.MthdRegisterPcb;

    [global::ProtoBuf.ProtoMember(2, Name = @"request_id", IsRequired = true)]
    public string RequestId { get; set; }

    [global::ProtoBuf.ProtoMember(20, Name = @"error", IsRequired = true)]
    public Error Error { get; set; } = Error.ErrServer;

    [global::ProtoBuf.ProtoMember(21, Name = @"error_msg")]
	public string ErrorMsg { get; set; }

    [global::ProtoBuf.ProtoMember(1001)]
    public Response.RegisterPcb register_pcb { get; set; }
    [global::ProtoBuf.ProtoMember(1002)]
    public Response.RegisterPcbAck register_pcb_ack { get; set; }

    [global::ProtoBuf.ProtoMember(1003)]
    public Response.SaveInsideData save_inside_data { get; set; }
	
    [global::ProtoBuf.ProtoMember(1004)]
    public Response2.LoadGameData load_game_data { get; set; }

    [global::ProtoBuf.ProtoMember(1005)]
    public Response2.LoadRankMatch2 load_rank_match { get; set; }

    [global::ProtoBuf.ProtoMember(1006)]
    public Response2.LoadClassMatch load_class_match { get; set; }

    [global::ProtoBuf.ProtoMember(1100)]
    public Response2.PreLoadCard pre_load_card { get; set; }
    [global::ProtoBuf.ProtoMember(1101)]
    public Response2.LoadCard load_card { get; set; }
	
    [global::ProtoBuf.ProtoMember(1102)]
    public Response.RegisterCard register_card { get; set; }

    [global::ProtoBuf.ProtoMember(1401)]
    public Response2.LoadRanking load_ranking { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192