// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace nue.protocol.exvs;

public partial class Response
{
    [global::ProtoBuf.ProtoMember(1418)]
    public LoadRoom load_room { get; set; }
    
    [global::ProtoBuf.ProtoMember(1419)]
    public RegisterRoom register_room { get; set; }
    
    // 1419
    [global::ProtoBuf.ProtoContract()]
    public partial class RegisterRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"status", IsRequired = true)]
        public uint Status { get; set; }
    }
    
    // 1418
    [global::ProtoBuf.ProtoContract()]
    public partial class LoadRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1, Name = @"pilot_id", IsRequired = true)]
        public uint PilotId { get; set; }
        
        [global::ProtoBuf.ProtoMember(2, Name = @"is_new_card", IsRequired = true)]
        public bool IsNewCard { get; set; }
        
        [global::ProtoBuf.ProtoMember(3, Name = @"rooms")]
        public global::System.Collections.Generic.List<RoomGroup> Rooms { get; } = new();
        
        [global::ProtoBuf.ProtoMember(4, Name = @"status", IsRequired = true)]
        public uint Status { get; set; }
        
        [global::ProtoBuf.ProtoMember(5, Name = @"acid_error")]
        [global::System.ComponentModel.DefaultValue(AcidError.AcidSuccess)]
        public AcidError AcidError
        {
            get => __pbn__AcidError ?? AcidError.AcidSuccess;
            set => __pbn__AcidError = value;
        }
        public bool ShouldSerializeAcidError() => __pbn__AcidError != null;
        public void ResetAcidError() => __pbn__AcidError = null;
        private AcidError? __pbn__AcidError;
        
        [global::ProtoBuf.ProtoContract()]
        public partial class RoomGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            
            [global::ProtoBuf.ProtoMember(1, Name = @"tag_id", IsRequired = true)]
            public uint TagId { get; set; }
            
            [global::ProtoBuf.ProtoMember(2, Name = @"registration_code", IsRequired = true)]
            public string RegistrationCode { get; set; }
            
            [global::ProtoBuf.ProtoMember(3, Name = @"tag_type", IsRequired = true)]
            public uint TagType { get; set; }
            
            [global::ProtoBuf.ProtoMember(4, Name = @"matching_type", IsRequired = true)]
            public uint MatchingType { get; set; }
            
            [global::ProtoBuf.ProtoMember(5, Name = @"start_date", IsRequired = true)]
            public ulong StartDate { get; set; }
            [global::ProtoBuf.ProtoMember(6, Name = @"end_date", IsRequired = true)]
            public ulong EndDate { get; set; }
            
            [global::ProtoBuf.ProtoMember(7, Name = @"current_num", IsRequired = true)]
            public uint CurrentNum { get; set; }
            
            [global::ProtoBuf.ProtoMember(8, Name = @"member_limit", IsRequired = true)]
            public uint MemberLimit { get; set; }
            
            [global::ProtoBuf.ProtoMember(9, Name = @"win_rate_min", IsRequired = true)]
            public uint WinRateMin { get; set; }
            [global::ProtoBuf.ProtoMember(10, Name = @"win_rate_max", IsRequired = true)]
            public uint WinRateMax { get; set; }
            
            [global::ProtoBuf.ProtoMember(11, Name = @"class_id_min", IsRequired = true)]
            public uint ClassIdMin { get; set; }
            [global::ProtoBuf.ProtoMember(12, Name = @"class_id_min", IsRequired = true)]
            public uint ClassIdMax { get; set; }
            
            [global::ProtoBuf.ProtoMember(13, Name = @"grade_id_min", IsRequired = true)]
            public uint GradeIdMin { get; set; }
            [global::ProtoBuf.ProtoMember(14, Name = @"grade_id_max", IsRequired = true)]
            public uint GradeIdMax { get; set; }
            
            [global::ProtoBuf.ProtoMember(15, Name = @"rule_type", IsRequired = true)]
            public uint RuleType { get; set; }
            
            [global::ProtoBuf.ProtoMember(16, Name = @"fes_rule_type", IsRequired = true)]
            public uint FesRuleType { get; set; }
            
            [global::ProtoBuf.ProtoMember(17, Name = @"policy", IsRequired = true)]
            public uint Policy { get; set; }

        }
    }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192