<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ServerIbOnOver</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ServerOver</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <!-- for 'dotnet run' cwd -->
    <RunWorkingDirectory>$(MSBuildThisFileDirectory)\bin\$(Configuration)\$(TargetFramework)\win-x64</RunWorkingDirectory>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Extensions\**" />
    <Compile Remove="Services\**" />
    <Content Remove="Extensions\**" />
    <Content Remove="Services\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Extensions\**" />
    <None Remove="Services\**" />
    <None Update="Certificates\cert.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\root.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ErrorOr" Version="2.1.1" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="MinimalApis.Extensions" Version="0.11.0" />
    <PackageReference Include="protobuf-net" Version="3.2.56" />
    <PackageReference Include="protobuf-net.AspNetCore" Version="3.2.52" />
    <!--<PackageReference Include="Quartz" Version="3.7.0" />-->
    <!--<PackageReference Include="Quartz.Extensions.Hosting" Version="3.7.0" />-->
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3mc" Version="2.1.11" />
    <PackageReference Include="Swan.Core" Version="7.0.0-beta.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Certificates\root.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Certificates\cert.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\_content\MudBlazor\" />
    <Folder Include="wwwroot\_framework\en-US\" />
    <Folder Include="wwwroot\_framework\ja\" />
    <Folder Include="wwwroot\_framework\zh-Hans\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Condition=" '$(DesignTimeBuild)'!='true' " Include="..\WebUIOver\Client\WebUIOver.Client.csproj" />
    <ProjectReference Include="..\WebUIOver\Shared\WebUIOver.Shared.csproj" />
  </ItemGroup>
</Project>